// Master Arabic-English Translation Dictionary for Fahim Mobile App
// Auto-generated from master curriculum dictionary with 3,280+ verified entries

const Map<String, String> kArabicMobileDict = {
  'آخره': 'its end / at its end',
  'أ': 'question particle / A',
  'أب': 'father',
  'أبحث': 'I search / seek',
  'أبدا': 'never',
  'أبعاد': 'dimensions / size',
  'أبيض': 'white (masc.)',
  'أتحدث': 'I speak',
  'أتدرب': 'I train / practice',
  'أتقن': 'I master / perfect',
  'أتم': 'completed / concluded',
  'أتى': 'arrived / came',
  'أثر': 'impact / effect / trace',
  'أثناء': 'during / while',
  'أجاب': 'answered',
  'أجداد': 'ancestors / forefathers',
  'أجيال': 'generations',
  'أحب': 'loved / liked',
  'أحجامها': 'their sizes / dimensions',
  'أحد': 'one / someone / Sunday',
  'أحد_عشر': '11 (eleven)',
  'أحدث': 'newer / newest',
  'أحدهم': 'one of them',
  'أحرز': 'scored / achieved',
  'أحسنت': 'well done! / excellent job!',
  'أحصنة': 'horses',
  'أحمد': 'Ahmad (proper name)',
  'أحمر': 'red (masc.)',
  'أحيانا': 'sometimes',
  'أخ': 'brother',
  'أخبرني': 'tell me!',
  'أخت': 'sister',
  'أخذ': 'took',
  'أخضر': 'green (masc.)',
  'أخطاء': 'fouls / mistakes',
  'أداء': 'performance / execution',
  'أربع': '4 (four - fem.)',
  'أربعة': '4 (four)',
  'أربعون': '40 (forty)',
  'أربعين': '40 (forty)',
  'أرض': 'ground / land / pitch',
  'أركانها': 'its pillars / elements',
  'أزرق': 'blue (masc.)',
  'أسئلة': 'questions',
  'أسابيع': 'weeks',
  'أساس': 'basis / foundation',
  'أساسي': 'basic / fundamental / primary',
  'أساسيا': 'basically / fundamentally',
  'أساسية': 'basic / primary (fem.)',
  'أسبوع': 'week',
  'أستمع': 'I listen',
  'أسرة': 'family',
  'أسرع': 'faster / fastest',
  'أسماء': 'nouns / names',
  'أسود': 'black (masc.)',
  'أشخاص': 'people / persons',
  'أشكال': 'shapes',
  'أشهر': 'more / most famous',
  'أشواط': 'halves / rounds',
  'أصالة': 'authenticity / nobility',
  'أصبت': 'you hit the mark / well done',
  'أصدقاء': 'friends',
  'أصغر': 'smaller / smallest',
  'أصفر': 'yellow (masc.)',
  'أصلية': 'primary / original (mark)',
  'أصنف': 'I classify / categorize',
  'أصيب': 'was injured / hit',
  'أصيل': 'authentic / thoroughbred',
  'أصيلة': 'thoroughbred (fem.)',
  'أطلق': 'launched / gave title',
  'أطول': 'longer / longest',
  'أعداد': 'numbers',
  'أعطى': 'gave',
  'أعلنت': 'announced / declared',
  'أعوام': 'years',
  'أغلق': 'closed',
  'أفراد': 'individuals',
  'أفضل': 'better / best',
  'أفعال': 'verbs',
  'أقبل': 'arrived / stepped forward',
  'أقدم': 'older / oldest',
  'أقصر': 'shorter / shortest',
  'أقل': 'less / least',
  'أكبر': 'bigger / largest',
  'أكثر': 'more / most',
  'أكل': 'ate',
  'أكمل': 'complete!',
  'ألعاب': 'games / sports',
  'ألعب': 'I play',
  'ألف': '1,000 (one thousand)',
  'ألفا': 'thousand (accusative)',
  'ألوان': 'colors',
  'أم': 'mother',
  'أما': 'as for / whereas',
  'أماكن': 'places',
  'أمام': 'in front of',
  'أمتار': 'meters',
  'أمثلة': 'examples',
  'أمر': 'matter / command / issue',
  'أمريكية': 'American',
  'أمس': 'yesterday',
  'أن': 'that / to',
  'أنا': 'I',
  'أنت': 'you',
  'أنواع': 'types / varieties',
  'أهداف': 'goals',
  'أهدافا': 'goals (accusative)',
  'أهلا': 'welcome / hello',
  'أهم': 'more / most important',
  'أو': 'or',
  'أولا': 'firstly / first',
  'أولى': 'first (fem.) / primary',
  'أولية': 'elementary / initial',
  'أي': 'which / any',
  'أيام': 'days',
  'أيضا': 'also / too',
  'أين': 'where',
  'أيها': 'O / you (vocative)',
  'إ': 'E (letter)',
  'إبداع': 'creativity / innovation',
  'إبراهيم': 'Ibrahim (proper name)',
  'إتقان': 'mastery / proficiency',
  'إثارة': 'excitement / thrill',
  'إثارتها': 'its excitement / thrill',
  'إجابة': 'answer / response',
  'إجابتك': 'your answer',
  'إجازة': 'vacation / leave',
  'إذا': 'if / when',
  'إسلامي': 'Islamic (masc.)',
  'إسلامية': 'Islamic (fem.)',
  'إسناد': 'verb conjugation / attribution',
  'إشارات': 'signals',
  'إشارة': 'signal / cue',
  'إصابات': 'injuries',
  'إصابة': 'injury',
  'إضافي': 'additional / extra',
  'إعراب': 'grammatical inflection / parsing',
  'إفطار': 'breakfast',
  'إلى': 'to / toward',
  'إلى_اللقاء': 'see you soon',
  'إملائيا': 'orthographically / spelling-wise',
  'إن': 'indeed / truly',
  'إنذار': 'warning / caution',
  'ا': 'Alif (letter)',
  'ابطال': 'Heroes',
  'ابناءها': 'Her children',
  'ابهام': 'thumb',
  'ابهر': 'Impress',
  'ابو': 'Abu',
  'ابوظبي': 'Abu Dhabi',
  'ات': 'plural suffix (-at)',
  'اتابع': 'I follow',
  'اتامل': 'I hope',
  'اتباع': 'followers',
  'اتتبع': 'I track',
  'اتذكر': 'I remember / recall',
  'اتعاون': 'I collaborate / cooperate',
  'اتمام': 'Completion',
  'اتمنى': 'I hope',
  'اتناول': 'I eat',
  'اثرائي': 'My enrichment',
  'اثنا_عشر': '12 (twelve)',
  'اثنان': '2 (two)',
  'اثنتان': '2 (two - fem.)',
  'اثنين': '2 (two)',
  'اجب': 'Answer',
  'اجتماعي': 'social (masc.)',
  'اجتماعية': 'social (fem.)',
  'اجل': 'Yes',
  'اجلس': 'I sit',
  'اجمل': 'More beautiful',
  'اجهاد': 'straining / muscle fatigue',
  'اجهزة': 'Devices',
  'احترام': 'respect',
  'احترم': 'Respect',
  'احتساب': 'awarding / adding time',
  'احتفل': 'I celebrate / commemorate',
  'احتكاكي': 'contact / physical clash',
  'احجام': 'sizes / dimensions',
  'احرص': 'Be careful',
  'اخبرك': 'Tell you',
  'اختبار': 'test / quiz',
  'اختر': 'choose! (imperative)',
  'اختيار': 'choosing / selecting',
  'اختيارك': 'your choice / selection',
  'اخر': 'Another',
  'اخرى': 'another / other (fem.)',
  'اخطط': 'I plan',
  'اخفاء': 'Hide',
  'اخلاقي': 'Ethical',
  'اخي': 'My brother',
  'ادارة': 'Management',
  'ادبية': 'Literary',
  'ادرس': 'I study / learn',
  'ادم': 'Adam',
  'ادوات': 'tools / equipment',
  'ارادة': 'Will',
  'ارتب': 'Get confused',
  'ارتداء': 'wear',
  'ارتدت': 'She bounced',
  'ارتديت': 'I wore',
  'ارتفعت': 'rose',
  'ارجع': 'Come back',
  'ارسال': 'sending / submitting',
  'ارسل': 'Send',
  'ارشادي': 'Heuristic',
  'ارقام': 'Numbers',
  'ارى': 'I see',
  'اسأل': 'ask! (imperative)',
  'اساعد': 'I help',
  'اساعدك': 'I help you',
  'استئناف': 'Resume',
  'استبدال': 'replace',
  'استبيان': 'survey / questionnaire',
  'استثنائي': 'exceptional / extraordinary',
  'استخدام': 'Use',
  'استخدم': 'I use / utilize',
  'استخرج': 'extract / identify!',
  'استراحة': 'halftime break / rest',
  'استرجع': 'retrieve / recall!',
  'استطاع': 'was able to / managed',
  'استطيع': 'I can',
  'استعد': 'get ready / prepare!',
  'استعداد': 'Ready',
  'استعراض': 'Reviews',
  'استعين': 'I utilize / seek assistance with',
  'استفسارك': 'your inquiry / question',
  'استكشافها': 'exploring it',
  'استلام': 'Receipt',
  'استماع': 'listening / audition',
  'استمتع': 'enjoyed',
  'استمرارية': 'continuity',
  'استمع': 'listen!',
  'استنتاج': 'deduction / conclusion',
  'استنتاجها': 'deducing it / its inference',
  'استنتج': 'deduce / infer!',
  'استوديو': 'studio',
  'استيعاب': 'comprehension / grasp',
  'استيقظ': 'woke up',
  'اسعدتني': 'You made me happy',
  'اسلوب': 'style / grammatical method',
  'اسم': 'noun / name',
  'اسمية': 'nominal (sentence starting with noun)',
  'اشارك': 'I participate / partner with',
  'اشاهد': 'I watch / observe',
  'اشتريت': 'I bought',
  'اشتقت': 'I missed / longed for',
  'اشجار': 'trees',
  'اشعر': 'I feel',
  'اشكركم': 'Thank you',
  'اشياء': 'Things',
  'اصابع': 'fingers',
  'اصحاب': 'Friends',
  'اصدقائي': 'My friends',
  'اصطناعي': 'artificial / synthetic (turf)',
  'اصعب': 'Harder',
  'اصف': 'Describe',
  'اصل': 'Origin',
  'اصمم': 'Design',
  'اضافة': 'Addition',
  'اضغط': 'Click',
  'اظهار': 'Show',
  'اعادة': 'Replay',
  'اعبر': 'Cross',
  'اعتزاز': 'pride / cherishing',
  'اعتماد': 'reliance / accreditation',
  'اعددت': 'I prepared',
  'اعرف': 'I know',
  'اعرفها': 'I know them / I recognize',
  'اعلان': 'Advertisement',
  'اعلانا': 'Advertisement',
  'اعلى': 'higher',
  'اعود': 'I return / come back',
  'اعيد': 'I repeat / rewrite',
  'اغلاق': 'Close',
  'اغنى': 'Richer',
  'افاقه': 'He woke up',
  'افتراضية': 'Virtual',
  'افريقيا': 'Africa',
  'افعلها': 'Do it',
  'اقارن': 'I compare',
  'اقتراحك': 'Your suggestion',
  'اقتربت': 'you came close / approached',
  'اقرأ': 'read!',
  'اقضي': 'spend',
  'اقلام': 'Pens',
  'اكاديمي': 'Academic',
  'اكتب': 'write!',
  'اكتشاف': 'discovering / identifying',
  'اكمال': 'Complete',
  'ال': 'the (definite article)',
  'الآباء': 'the fathers / parents',
  'الآن': 'now',
  'الأبعاد': 'the dimensions',
  'الأجداد': 'the ancestors',
  'الأجيال': 'the generations',
  'الأخطاء': 'the mistakes / errors',
  'الأخير': 'the last / final (masc.)',
  'الأخيرة': 'the last / final (fem.)',
  'الأرض': 'the land / ground / pitch',
  'الأساسية': 'the basic / primary (fem.)',
  'الأساسيين': 'the starting / primary (players)',
  'الأشكال': 'the shapes',
  'الأصالة': 'the authenticity',
  'الأصلي': 'the original / primary',
  'الأصلية': 'the primary mark',
  'الأعظم': 'the greatest',
  'الأفضل': 'the best',
  'الأفعال': 'the verbs',
  'الأكبر': 'the biggest / largest',
  'الأكثر': 'the most',
  'الأمر': 'the matter / the command',
  'الأمريكية': 'American (fem.)',
  'الأنشطة': 'activities',
  'الأهداف': 'the goals',
  'الأوسمة': 'badges / achievement honors',
  'الأول': 'the first (masc.)',
  'الأولى': 'the first (fem.)',
  'الأيام': 'the days',
  'الإبداع': 'Creativity & Innovation',
  'الإتقان': 'mastery / proficiency',
  'الإثارة': 'the excitement',
  'الإجمالي': 'the total / overall',
  'الإسلامية': 'Islamic (fem.)',
  'الإشباع': 'vowel lengthening / phonological saturation',
  'الإضافي': 'the additional (injury time)',
  'الإعراب': 'grammatical inflection',
  'الإلكترونية': 'electronic / digital',
  'الإمارات': 'the United Arab Emirates (UAE)',
  'الإملاء': 'orthography / spelling / dictation',
  'الإنجاز': 'achievement / accomplishment',
  'الإيقاع': 'rhythm / cadence',
  'الابتسامة': 'Smile',
  'الابتكار': 'Creation & Innovation',
  'الابطال': 'Heroes',
  'الابهام': 'the thumb (finger)',
  'الات': 'Machines',
  'الاتحاد': 'federation / union (e.g. FIFA / UAE FA)',
  'الاتصال': 'Contact',
  'الاثرائية': 'Enrichment',
  'الاحباط': 'Frustration',
  'الاحترام': 'the respect',
  'الاحتفاظ': 'retention',
  'الاحتكاكي': 'contact (sport with physical collision)',
  'الاحتياجات': 'needs',
  'الاختبارات': 'tests / quizzes',
  'الاختيار': 'the choice / selection',
  'الاخرى': 'The other',
  'الاخرين': 'others',
  'الاخلاق': 'Ethics',
  'الارتقاء': 'elevation / advancement',
  'الارشادي': 'The guideline',
  'الازياء': 'Fashion',
  'الاساءة': 'Abuse',
  'الاساليب': 'Methods',
  'الاستاذ': 'Professor',
  'الاستبيان': 'the survey / questionnaire',
  'الاستخدام': 'the usage / application',
  'الاستذكار': 'study review / revision',
  'الاستراحة': 'halftime break',
  'الاسترجاع': 'Retrieval & Recall',
  'الاستعداد': 'readiness / preparation',
  'الاستفسار': 'the inquiry / query',
  'الاستفهام': 'Interrogative',
  'الاستماع': 'listening / listening comprehension',
  'الاستمرارية': 'continuity',
  'الاستناد': 'Reliance',
  'الاستنتاج': 'Deduction & Inference',
  'الاستهزاء': 'Mocking',
  'الاستيعاب': 'comprehension / understanding',
  'الاسراف': 'Extravagance',
  'الاسري': 'The captive',
  'الاسم': 'the noun / name',
  'الاسمية': 'the nominal (sentence)',
  'الاشتراك': 'Subscribe',
  'الاشجار': 'the trees',
  'الاشياء': 'things',
  'الاصابع': 'the fingers',
  'الاصطناعي': 'artificial / synthetic',
  'الاطار': 'Frame',
  'الاطمئنان': 'Reassurance',
  'الاعاقة': 'Disability',
  'الاعتزاز': 'pride / cherishing',
  'الاعتماد': 'reliance / dependence',
  'الاعمال': 'Business',
  'الاعياد': 'Holidays',
  'الاغذية': 'Foods',
  'الافكار': 'Ideas',
  'الافلام': 'Movies',
  'الالات': 'The machines',
  'الالتزام': 'adherence / commitment',
  'الام': 'Mother',
  'الامان': 'Safety',
  'الامتحانات': 'exams / practice tests',
  'الامتيازات': 'Privileges',
  'الامور': 'Things',
  'الانترنت': 'Internet',
  'الانتقال': 'Transition',
  'الانجليزية': 'English',
  'الانزعاج': 'Discomfort',
  'الانضباط': 'Discipline',
  'الانيق': 'Elegant',
  'الاهتمام': 'Attention',
  'الاهمال': 'carelessness / negligence',
  'الاوساخ': 'Dirt',
  'الايجابي': 'Positive',
  'الباقات': 'Packages',
  'الباقة': 'Package',
  'البالغ': 'reaching / amounting to',
  'البحث': 'Search',
  'البدء': 'commencement / beginning',
  'البداية': 'the start',
  'البدلاء': 'the substitutes',
  'البدنية': 'physical (e.g. Physical Education)',
  'البديل': 'the alternative / substitute',
  'البرازيل': 'Brazil (famed football nation)',
  'البرونز': 'Bronze',
  'البرونزية': 'the bronze medal',
  'البريطاني': 'British',
  'البس': 'Dress up',
  'البسيطة': 'Simple',
  'البطاقة': 'the card',
  'البطل': 'the champion / hero',
  'البطولات': 'championships / tournaments',
  'البطولة': 'championship / tournament',
  'البلاد': 'the country / nations',
  'البناء': 'structure / construction',
  'البنت': 'the girl',
  'البنصر': 'the ring finger',
  'البولو': 'polo (equestrian ball game)',
  'البولينج': 'bowling',
  'البيان': 'Statement',
  'البيت': 'the house / home',
  'البيضة': 'the egg (oval reference)',
  'البيضوي': 'the oval shape',
  'البيع': 'sale',
  'التأسيسي': 'foundational',
  'التأكيد': 'emphasis / confirmation',
  'التأنيث': 'feminine marker',
  'التاسيس': 'Founding',
  'التالي': 'the following / next',
  'التالية': 'the following (fem.)',
  'التبديل': 'the substitution',
  'التجاهل': 'Ignoring',
  'التجريبي': 'practice / mock trial',
  'التحدي': 'the challenge',
  'التحري': 'investigation / verification',
  'التحريك': 'vowelling / vocalization',
  'التحصيل': 'Collection',
  'التحفيز': 'Motivation',
  'التحكيم': 'refereeing / officiating',
  'التحليل': 'Analysis & Examination',
  'التحميل': 'Download',
  'التخطيط': 'planning',
  'التدرج': 'progression / graduation',
  'التدريب': 'training / practice',
  'التدريبات': 'exercises / drills',
  'التدفق': 'Flow',
  'التذكر': 'Recall & Retrieval',
  'التذكير': 'masculine gender',
  'التراث': 'the heritage',
  'التراكيب': 'sentence structures',
  'التربة': 'Soil',
  'التربية': 'education / upbringing',
  'الترتيب': 'order / arrangement',
  'الترجمة': 'Translation',
  'الترقيم': 'Numbering',
  'التركيز': 'focus / concentration',
  'التزام': 'adherence / commitment',
  'التسجيل': 'scoring / registration',
  'التسديد': 'shooting / striking',
  'التسمية': 'the title / designation',
  'التصادم': 'collision / crashing',
  'التصحيح': 'Correction',
  'التصرف': 'Act',
  'التصنيف': 'Classification & Grouping',
  'التصويب': 'correction / aiming',
  'التطبيق': 'Application & Practice',
  'التطوير': 'Development',
  'التعاون': 'the cooperation',
  'التعبير': 'expression / composition',
  'التعبيرية': 'Expressionism',
  'التعجب': 'Exclamation',
  'التعرف': 'Recognition',
  'التعريف': 'the definition',
  'التعلم': 'learning / education',
  'التعليم': 'instruction / teaching',
  'التعليمات': 'instructions / directions',
  'التغيير': 'change / switch',
  'التفاعل': 'interaction',
  'التفكير': 'thinking / cognition',
  'التفوق': 'excellence / distinction',
  'التقاليد': 'traditions / customs',
  'التقدير': 'Appreciation',
  'التقديري': 'Estimated',
  'التقديمي': 'presentation / showcase',
  'التقليدي': 'Traditional',
  'التقليدية': 'traditional / heritage',
  'التقويمية': 'formative / diagnostic assessment',
  'التقييم': 'Evaluation & Judgment',
  'التكرار': 'repetition / drill',
  'التكنولوجيا': 'technology',
  'التكيفي': 'Adaptive',
  'التكيفية': 'Adaptive',
  'التلفاز': 'the television / TV',
  'التماثيل': 'Statues',
  'التمارين': 'exercises / drills',
  'التماس': 'throw-in / touchline',
  'التمثال': 'The statue',
  'التمرين': 'exercise / practice',
  'التمكن': 'Mastery',
  'التمكين': 'Empowerment',
  'التمييز': 'Distinction & Differentiation',
  'التنس': 'tennis',
  'التنظيم': 'Organization',
  'التنغيم': 'intonation / pitch contour',
  'التنقل': 'navigation / movement',
  'التنقيح': 'editing / revision',
  'التنوين': 'the Tanween',
  'التهيئة': 'Initialization',
  'التواصل': 'Communication',
  'التوجيه': 'guidance / orientation',
  'التوضيح': 'clarification / illustration',
  'التي': 'who / which (feminine)',
  'الثالث': 'the third',
  'الثاني': 'the second',
  'الثانية': 'the second (fem.)',
  'الثقة': 'Trust',
  'الجاذبة': 'attractive / captivating',
  'الجارفة': 'overwhelming (popularity)',
  'الجاري': 'ongoing / current',
  'الجاهزة': 'Ready made',
  'الجبن': 'Cheese',
  'الجد': 'Grandfather',
  'الجر': 'the genitive case / pulling',
  'الجري': 'running',
  'الجزء': 'part / section',
  'الجزاء': 'penalty box (18-yard area)',
  'الجلد': 'leather (ball casing)',
  'الجماعة': 'Community',
  'الجماهير': 'the fans / spectators',
  'الجملة': 'the sentence',
  'الجمهور': 'public / audience / spectators',
  'الجندرية': 'gender-related / gender concord',
  'الجنس': 'Sex',
  'الجهات': 'Entities',
  'الجهاز': 'the device / apparatus',
  'الجهد': 'effort / exertion',
  'الجوع': 'Hunger',
  'الجولف': 'golf',
  'الجوهري': 'fundamental / core difference',
  'الجيد': 'the good / sound',
  'الحائز': 'the winner / recipient',
  'الحاجز': 'Barrier',
  'الحاد': 'Acute',
  'الحادث': 'The accident',
  'الحارس': 'the goalkeeper',
  'الحاسوب': 'Computer',
  'الحافز': 'motive / incentive',
  'الحالي': 'current / present',
  'الحبوب': 'Cereals',
  'الحبيب': 'Beloved',
  'الحجارة': 'Stones',
  'الحجم': 'the size',
  'الحدث': 'Event',
  'الحديثة': 'modern / recent',
  'الحر': 'free (e.g. free kick / free style)',
  'الحركات': 'vowel marks / movements',
  'الحركة': 'vowel mark / movement',
  'الحصاد': 'Harvest',
  'الحصان': 'the horse',
  'الحصول': 'obtaining / achieving',
  'الحضور': 'Attendance',
  'الحفظ': 'memorization / preservation',
  'الحفيد': 'The grandson',
  'الحق': 'Right',
  'الحقائق': 'Facts',
  'الحقل': 'field',
  'الحقوق': 'Rights',
  'الحقيقة': 'truth / fact',
  'الحكام': 'the referees',
  'الحكم': 'the referee',
  'الحل': 'solution / answer',
  'الحلول': 'Solutions',
  'الحمراء': 'the red (card)',
  'الحواجز': 'the hurdles',
  'الحوار': 'dialogue / conversation',
  'الحي': 'the neighborhood / district',
  'الحيوانات': 'Animals',
  'الخاص': 'special / distinct',
  'الخامس': 'the fifth',
  'الخباز': 'The baker',
  'الخبر': 'the grammatical predicate',
  'الخبرة': 'experience / expertise',
  'الختامي': 'Closing',
  'الخروج': 'logout / exit',
  'الخشبي': 'Wooden',
  'الخصم': 'discount',
  'الخصوصي': 'private tutoring',
  'الخط': 'calligraphy / script',
  'الخطة': 'the study plan',
  'الخطوات': 'the steps / stages',
  'الخطوة': 'the step',
  'الخطوط': 'Fonts',
  'الخلاصة': 'Conclusion',
  'الخلق': 'Creation',
  'الخمسة': 'the five',
  'الخنصر': 'the pinky / little finger',
  'الخيار': 'the option / choice',
  'الخيارات': 'the options / choices',
  'الخيال': 'Imagination',
  'الخيالية': 'fictional / imaginative',
  'الخيل': 'the horses',
  'الداخلية': 'internal / interior',
  'الدراسي': 'academic / school-related',
  'الدراسية': 'Scholarship',
  'الدراهم': 'Dirhams',
  'الدرس': 'the lesson',
  'الدروس': 'the lessons',
  'الدقة': 'accuracy / precision',
  'الدقيقة': 'the minute',
  'الدليل': 'guide / evidence',
  'الدور': 'role / turn',
  'الدوري': 'league / tournament',
  'الدولي': 'international',
  'الدولية': 'international',
  'الذاتي': 'self / individual',
  'الذاتية': 'individual (skill)',
  'الذاكرة': 'memory',
  'الذكية': 'smart / adaptive',
  'الذهاب': 'Go',
  'الذهبية': 'the golden (medal)',
  'الذي': 'who / which (masculine)',
  'الذين': 'who / those who',
  'الرئيسة': 'the main / principal',
  'الرئيسي': 'main / chief / primary',
  'الرئيسية': 'main / principal (fem.)',
  'الرابع': 'the fourth (official)',
  'الراحة': 'Comfort',
  'الراسيتان': 'The two heads',
  'الراسيتين': 'Two heads',
  'الراغبين': 'Wishing',
  'الرد': 'Reply',
  'الرسالة': 'The message',
  'الرسمي': 'the official',
  'الرسمية': 'official (fem.)',
  'الرشيق': 'Graceful',
  'الرغم': 'despite / in spite of',
  'الرقم': 'number / digit',
  'الركبي': 'rugby sport',
  'الرمال': 'the sands',
  'الرماية': 'archery',
  'الرمز': 'Symbol',
  'الرمي': 'throwing / shooting',
  'الرواد': 'pioneers',
  'الروتين': 'Routine',
  'الروح': 'spirit (e.g. sportsmanship spirit)',
  'الرياضات': 'sports',
  'الرياضة': 'sport',
  'الرياضي': 'athlete / sportsman',
  'الرياضيات': 'mathematics / maths',
  'الرياضية': 'sporting / athletic (fem.)',
  'الرياضيون': 'athletes / sportsmen',
  'الزجاج': 'Glass',
  'الزراعة': 'Agriculture',
  'الزرع': 'Transplantation',
  'الزملاء': 'the classmates / peers',
  'الزمن': 'time / duration',
  'الزوار': 'Visitors',
  'الزي': 'The outfit',
  'السابق': 'previous / former',
  'السابقة': 'previous (fem.)',
  'الساحة': 'the main pitch (referee)',
  'الساحرة': 'the magician (the round one)',
  'السادس': 'Sixth',
  'الساري': 'Sari',
  'الساقين': 'the two shins / legs',
  'السبابة': 'the index finger',
  'السباحة': 'swimming',
  'السباق': 'the race',
  'السبت': 'Saturday',
  'السحري': 'magical',
  'السخرية': 'Sarcasm',
  'السرج': 'the saddle',
  'السرعة': 'speed / velocity',
  'السقراطي': 'Socratic tutoring',
  'السقوط': 'falling / falling down',
  'السكون': 'the Sukun mark',
  'السلة': 'the basket (basketball)',
  'السليم': 'sound / healthy',
  'السمبريرو': 'Sombrero',
  'السمة': 'characteristic / feature',
  'السندباد': 'Sinbad',
  'السنوي': 'Annual',
  'السيء': 'The bad',
  'السياق': 'context',
  'السيطرة': 'control / mastery',
  'الشامخ': 'The tall one',
  'الشامل': 'comprehensive (masc.)',
  'الشاملة': 'comprehensive (fem.)',
  'الشباك': 'the goal net',
  'الشبكة': 'the net (goal net / court net)',
  'الشجاعة': 'the courage',
  'الشخصية': 'personality / character',
  'الشدة': 'the Shaddah',
  'الشرح': 'the explanation',
  'الشرف': 'honor / prestige',
  'الشطرنج': 'Chess',
  'الشعبية': 'the popularity / popular',
  'الشعور': 'Feeling',
  'الشفتين': 'Lips',
  'الشفهية': 'Oral',
  'الشهير': 'famous / renowned',
  'الشوط': 'the half / round',
  'الشيء': 'The thing',
  'الشيخ': 'Sheikh',
  'الصالات': 'indoor sports halls',
  'الصالة': 'the gym / indoor hall',
  'الصبر': 'the patience',
  'الصبور': 'Patient',
  'الصحراء': 'the desert',
  'الصحيحة': 'the correct (fem.)',
  'الصداقة': 'Friendship',
  'الصرف': 'morphology',
  'الصعوبة': 'Difficulty',
  'الصغار': 'The little ones',
  'الصغير': 'small / young',
  'الصف': 'the class / grade',
  'الصفارة': 'referee whistle',
  'الصفحة': 'the page',
  'الصفراء': 'the yellow (card)',
  'الصق': 'Paste',
  'الصلب': 'solid / firm',
  'الصوت': 'sound / voice / audio',
  'الصوتية': 'audio / vocal (fem.)',
  'الصور': 'images / pictures',
  'الصورة': 'image / picture',
  'الصياغة': 'Drafting',
  'الصيد': 'hunting',
  'الضائع': 'added / injury time',
  'الضخم': 'The huge one',
  'الضد': 'The opposite',
  'الضريبية': 'tax',
  'الضعف': 'Weakness',
  'الضمة': 'the Dammah mark',
  'الضوئي': 'optical / barcode',
  'الطائرة': 'the volleyball',
  'الطب': 'Medicine',
  'الطبيعي': 'natural (grass pitch)',
  'الطحن': 'Grinding',
  'الطحين': 'Flour',
  'الطريقة': 'method / way',
  'الطعام': 'the food',
  'الطفل': 'The child',
  'الطلاب': 'the students',
  'الطلاقة': 'fluency',
  'الطلب': 'request / demand',
  'الطوارئ': 'Emergency',
  'الطول': 'the length',
  'الطيبة': 'Kindness',
  'الظاهر': 'apparent / visible',
  'الظهر': 'Noon',
  'الظهيرة': 'Noon',
  'العالم': 'the world',
  'العالمي': 'global / international',
  'العالية': 'high / elevated',
  'العباءة': 'the Abaya',
  'العبارات': 'phrases / expressions',
  'العبارة': 'phrase / expression',
  'العجيب': 'wondrous / astonishing',
  'العدالة': 'fairness (in sports)',
  'العدد': 'the number / count',
  'العربية': 'Arabic / the Arabic language',
  'العرض': 'the width',
  'العرضية': 'crossbar (goal) / cross pass',
  'العريقة': 'ancient / deep-rooted',
  'العزيز': 'Dear',
  'العصر': 'era / modern time / afternoon',
  'العضلات': 'the muscles',
  'العطف': 'Kindness',
  'العلامات': 'marks / signs',
  'العلامة': 'the inflection mark',
  'العلمي': 'scientific / academic',
  'العلوم': 'the sciences',
  'العمر': 'Age',
  'العمل': 'work / action',
  'العملي': 'practical',
  'العميل': 'Client',
  'العناية': 'care / attention',
  'العنصر': 'element / component',
  'العنف': 'violence / aggression',
  'العنوان': 'the title / headline',
  'العوامل': 'factors',
  'العودة': 'Return',
  'العيد': 'Eid',
  'العين': 'the eye / Al Ain',
  'الغاء': 'Cancel',
  'الغائب': 'Absentee',
  'الغامضة': 'The mysterious',
  'الغاية': 'The purpose',
  'الغذاء': 'Food',
  'الغزال': 'Deer',
  'الفائز': 'the winner',
  'الفائزون': 'the winners',
  'الفائقة': 'Super',
  'الفاتنة': 'fascinating',
  'الفاتورة': 'Invoice',
  'الفارس': 'the rider / equestrian',
  'الفارق': 'the difference / margin',
  'الفاصل': 'separator',
  'الفاعل': 'the grammatical subject',
  'الفتحة': 'the Fathah mark',
  'الفترة': 'period / interval',
  'الفجوات': 'Gaps',
  'الفجوة': 'gap',
  'الفراغ': 'fill-in-the-blank',
  'الفرق': 'the teams / the difference',
  'الفروسية': 'equestrianism',
  'الفريق': 'the team',
  'الفصاحة': 'Eloquence',
  'الفصول': 'Chapters',
  'الفضة': 'Silver',
  'الفضي': 'Silver',
  'الفعل': 'the verb',
  'الفعلية': 'the verbal (sentence)',
  'الفقرة': 'paragraph / passage',
  'الفكرة': 'the idea / thought',
  'الفلاح': 'The farmer',
  'الفن': 'the art',
  'الفنون': 'the arts',
  'الفهم': 'Understanding & Comprehension',
  'الفوائد': 'the benefits / advantages',
  'الفواتير': 'Invoices',
  'الفوري': 'Immediate',
  'الفونيم': 'phoneme / speech sound',
  'الفيفا': 'FIFA (World Football Governing Body)',
  'القائمة': 'List',
  'القادم': 'Next',
  'القارئ': 'the reader',
  'القاعدة': 'the grammar / game rule',
  'القانون': 'law / regulation',
  'القانوني': 'legal / official (pitch size)',
  'القانونية': 'legal / official',
  'القبيح': 'The ugly',
  'القدرة': 'ability / capacity',
  'القدم': 'the foot (football)',
  'القديمة': 'traditional / ancient',
  'القراءة': 'reading',
  'القرائي': 'Reader',
  'القرائية': 'Literacy',
  'القرن': 'century',
  'القسم': 'section / division',
  'القش': 'Straw',
  'القصير': 'the short (masc.)',
  'القصيرة': 'the short (fem.)',
  'القفطان': 'Kaftan',
  'القفل': 'lock',
  'القلب': 'the heart',
  'القلق': 'Anxiety',
  'القمة': 'the peak',
  'القواعد': 'the rules / grammar',
  'القوة': 'power / strength',
  'القول': 'Saying',
  'القوى': 'Curriculum Term',
  'القى': 'He threw',
  'القيادة': 'Driving',
  'القياسية': 'record-breaking',
  'القيم': 'the values',
  'الكامل': 'complete / full (masc.)',
  'الكاملة': 'complete / full (fem.)',
  'الكبار': 'Adults',
  'الكبسولات': 'learning capsules (micro-lessons)',
  'الكتاب': 'the book',
  'الكتابة': 'writing',
  'الكترونية': 'Electronic',
  'الكرة': 'the ball',
  'الكريكت': 'cricket',
  'الكسرة': 'the Kasrah mark',
  'الكفاءات': 'Competencies',
  'الكلام': 'speech / spoken words',
  'الكلمات': 'the words / vocabulary',
  'الكلمة': 'the word',
  'الكلي': 'the overall / total / holistic',
  'الكندورة': 'the Kandura',
  'الكيمونو': 'Kimono',
  'اللازمة': 'necessary / required',
  'اللاعب': 'the player',
  'اللاعبان': 'the two players',
  'اللاعبون': 'the players (nominative)',
  'اللاعبين': 'the players',
  'اللجام': 'the bridle',
  'اللحظات': 'the moments',
  'اللعب': 'playing / game',
  'اللغة': 'the language',
  'اللغوي': 'linguistic',
  'اللقاء': 'The meeting',
  'اللقب': 'Curriculum Term',
  'الله': 'God',
  'اللوحة': 'the painting',
  'اللوفر': 'Louvre',
  'المؤدب': 'The polite one',
  'المؤسس': 'founder',
  'المؤكد': 'confirmed / certain',
  'المؤلف': 'Author',
  'المؤنث': 'the feminine',
  'المئتان': 'two hundred',
  'المئوية': 'percentage / century',
  'المائة': 'one hundred',
  'المائدة': 'The table',
  'الماسح': 'the scanner / barcode reader',
  'الماهر': 'skilled player',
  'المباراة': 'the match / game',
  'المبارتان': 'the two matches',
  'المبتدأ': 'the nominal subject',
  'المبدئي': 'initial / preliminary',
  'المتابعة': 'following / audience',
  'المتاجر': 'Stores',
  'المتبادل': 'mutual / reciprocal',
  'المتباعد': 'spaced / distanced',
  'المتبقي': 'remaining / leftover',
  'المتتابعة': 'successive / consecutive',
  'المتجر': 'the reward store',
  'المتحدة': 'United',
  'المتحدث': 'speaker',
  'المتدرب': 'trainee / student',
  'المتصدرون': 'Leaderboards',
  'المتصفح': 'Browser',
  'المتصلة': 'attached (pronoun)',
  'المتعلم': 'learner / student',
  'المتقدم': 'advanced',
  'المتكلم': 'Speaker',
  'المتميز': 'distinguished / outstanding',
  'المتوسط': 'intermediate / average',
  'المثال': 'the example',
  'المثالي': 'ideal / exemplary',
  'المجال': 'field / domain',
  'المجانية': 'Free',
  'المجتمع': 'society / community',
  'المجتهد': 'Hardworking',
  'المجدولة': 'Scheduled',
  'المجلد': 'volume / tome',
  'المجموع': 'sum / aggregate',
  'المجموعة': 'group / set',
  'المحادثة': 'Conversation',
  'المحبة': 'Loving',
  'المحترف': 'professional (athlete)',
  'المحترفة': 'professional (fem.)',
  'المحميات': 'Reserves',
  'المحور': 'axis / theme',
  'المحيط': 'ocean / perimeter / surrounding',
  'المخاطب': 'Addressee',
  'المخاطر': 'the risks / hazards',
  'المخرج': 'phonetic articulation point',
  'المخطط': 'diagram / plan',
  'المدارس': 'Schools',
  'المدرب': 'coach / trainer',
  'المدربين': 'coaches / trainers',
  'المدرسة': 'the school',
  'المدرسي': 'the school (adj. masc.) / scholastic',
  'المدرسية': 'school (adj. fem.) / educational',
  'المدير': 'Manager',
  'المدينة': 'the city',
  'المذاكرة': 'study / revision mode',
  'المذكر': 'the masculine',
  'المذكرة': 'notebook / study brief',
  'المراجعة': 'revision / review',
  'المراحل': 'Stages',
  'المربوطة': 'the tied Taa',
  'المرتفع': 'high / elevated',
  'المرح': 'the fun',
  'المرحلة': 'stage / grade level',
  'المرسوم': 'drawn / charted',
  'المرمى': 'the goal net / goal post',
  'المزارع': 'Farmer',
  'المزدوج': 'Dual',
  'المزعجة': 'Annoying',
  'المسؤول': 'official / responsible',
  'المسابقات': 'competitions / contests',
  'المسابقة': 'competition / contest',
  'المسار': 'path / course / track',
  'المساعد': 'the assistant',
  'المسافة': 'distance',
  'المستحق': 'deserved / entitled',
  'المستخلص': 'summary / extract',
  'المستقل': 'independent',
  'المستقيمة': 'straight (line)',
  'المستمر': 'continuous / ongoing',
  'المستهدفة': 'Targeted',
  'المستوى': 'level / grade',
  'المسجل': 'recorded / registered',
  'المسموع': 'the audio / heard text',
  'المشاركة': 'participation / sharing',
  'المشاعر': 'Feelings',
  'المشجعين': 'the fans / supporters',
  'المشروع': 'project / enterprise',
  'المشكلة': 'The problem',
  'المشهور': 'famous / renowned (masc.)',
  'المشهورة': 'famous / renowned (fem.)',
  'المشوقة': 'Interesting',
  'المصانع': 'the factories / plants',
  'المصور': 'Photographer',
  'المصورة': 'Illustrated',
  'المضارع': 'present tense (verb)',
  'المضافة': 'added',
  'المضرب': 'the racket / bat',
  'المضمار': 'the racetrack',
  'المطاحن': 'Mills',
  'المطاط': 'rubber casing',
  'المطرز': 'Embroidered',
  'المطلوب': 'required / requested',
  'المظهر': 'Appearance',
  'المعارف': 'knowledge / insights',
  'المعالجة': 'Processing',
  'المعاني': 'Meanings',
  'المعايرة': 'level calibration / assessment',
  'المعايير': 'standards / benchmarks',
  'المعتمد': 'Approved',
  'المعتمدة': 'approved / accredited',
  'المعجم': 'dictionary / glossary',
  'المعدة': 'Stomach',
  'المعرفي': 'Cognitive',
  'المعرفية': 'Cognitive',
  'المعززة': 'The booster',
  'المعلم': 'the teacher',
  'المعنى': 'the meaning / sense',
  'المغربي': 'Moroccan',
  'المغربية': 'Moroccan',
  'المغلقة': 'closed / indoor (hall)',
  'المفاجئ': 'Sudden',
  'المفاهيم': 'concepts',
  'المفتوحة': 'the open Taa',
  'المفردات': 'vocabulary / glossary',
  'المفضلة': 'favorite',
  'المفعلة': 'Activated',
  'المفهوم': 'concept / understood',
  'المقابلة': 'match / meeting / interview',
  'المقارنة': 'Comparison',
  'المقترحة': 'proposed',
  'المقدار': 'amount / degree',
  'المقدرة': 'latent inflection mark',
  'المقر': 'Headquarters',
  'المقرر': 'prescribed syllabus / text',
  'المقروء': 'the reading passage',
  'المقصود': 'intended / meant',
  'المكتبة': 'the library',
  'المكسيك': 'Mexico',
  'الملابس': 'the clothes',
  'الملاحظات': 'quick review notes',
  'الملازم': 'study booklets / summaries',
  'الملايين': 'the millions',
  'الملخص': 'Summary',
  'الملعب': 'the pitch / stadium / field',
  'الملكية': 'possessive suffix',
  'الممسوح': 'The anointed one',
  'المملكة': 'Kingdom',
  'المميز': 'distinctive / special',
  'المناسب': 'suitable / appropriate',
  'المناسبة': 'suitable (fem.) / occasion',
  'المنافس': 'competitor / opponent',
  'المنافسات': 'competitions',
  'المنافسة': 'competition / rivalry',
  'المناقشة': 'the discussion',
  'المنتجات': 'Products',
  'المنصة': 'platform / podium',
  'المنطقية': 'Logical',
  'المنفرة': 'repelling / discordant',
  'المنهاج': 'the curriculum / syllabus',
  'المها': 'Oryx',
  'المهارات': 'skills',
  'المهارة': 'skill',
  'المهام': 'the tasks / assignments',
  'المهمات': 'tasks / missions',
  'المهمة': 'task / mission / important',
  'المواقف': 'situations / attitudes',
  'الموجه': 'guided practice',
  'الموز': 'Banana',
  'الموسوعات': 'Encyclopedias',
  'الموسوعة': 'the encyclopedia',
  'الموقع': 'website / position / location',
  'الموقف': 'Attitude',
  'الموناليزا': 'the Mona Lisa',
  'الميدالية': 'the medal',
  'الميدان': 'field / arena',
  'الناجح': 'successful',
  'النادي': 'sports club',
  'الناس': 'People',
  'الناصع': 'Spotless',
  'الناهية': 'The end',
  'النتائج': 'results / scores',
  'النتيجة': 'result / score',
  'النحات': 'Sculptor',
  'النحت': 'Sculpture',
  'النخبة': 'Elite',
  'النخلة': 'The palm tree',
  'النسبة': 'Ratio',
  'النسخ': 'Copy',
  'النسخة': 'Version',
  'النسوة': 'Women',
  'النشاط': 'activity / drill',
  'النشرة': 'Bulletin',
  'النص': 'text / passage',
  'النصوص': 'texts / passages',
  'النطاق': 'scope',
  'النطق': 'pronunciation',
  'النظم': 'Systems',
  'النعت': 'Adjective',
  'النعيمي': 'Al Nuaimi',
  'النقطة': 'point / dot',
  'النماذج': 'models / samples',
  'النموذج': 'model / sample / exemplar',
  'النهائي': 'final (match)',
  'النهائية': 'final (fem.)',
  'النهاية': 'the finish line',
  'النهر': 'the river',
  'النهي': 'prohibition / negative imperative',
  'النوع': 'the type / kind',
  'الهاء': 'the letter Haa',
  'الهامش': 'margin',
  'الهدف': 'the goal',
  'الهدفان': 'the two goals',
  'الهدية': 'The gift',
  'الهمزة': 'the Hamza',
  'الهمم': 'determination (People of Determination)',
  'الهندي': 'Indian',
  'الهوايات': 'hobbies',
  'الهواية': 'hobby',
  'الهول': 'The sphinx',
  'الهوية': 'UAE national identity',
  'الهيكل': 'structure / framework',
  'الواحة': 'The oasis',
  'الواردة': 'mentioned / listed',
  'الواضح': 'clear / evident',
  'الواقع': 'reality / fact',
  'الوالدين': 'Parents',
  'الواو': 'letter Waw',
  'الوثائقية': 'Documentary',
  'الوحدات': 'units / chapters',
  'الوحدة': 'unit / chapter',
  'الوزارة': 'Ministry of Education (MoE)',
  'الوزاري': 'ministerial / official exam',
  'الوزارية': 'ministerial (exam model)',
  'الوزن': 'weight / meter',
  'الوسط': 'center / midfield',
  'الوسطى': 'the middle finger / central',
  'الوصف': 'Description',
  'الوصفية': 'Descriptive',
  'الوصول': 'arrival / reaching',
  'الوضع': 'status / mode / position',
  'الوضوح': 'clarity',
  'الوطن': 'the homeland',
  'الوظيفة': 'function / job / role',
  'الوقت': 'the time',
  'الوقف': 'pausing on word ending',
  'الوقوف': 'standing',
  'الولد': 'the boy',
  'الياباني': 'Japanese',
  'اليد': 'the hand (handball)',
  'اليشا': 'Elisha',
  'اليوم': 'today',
  'اليومي': 'daily (masc.)',
  'اليومية': 'daily (fem.)',
  'امارة': 'Principality',
  'امتحان': 'exam / test',
  'امتحانات': 'exams / tests',
  'املا': 'I fill out / complete',
  'املائية': 'Spelling',
  'امنة': 'Amina (proper name) / safe',
  'امي': 'My mother',
  'اناقش': 'I discuss / debate',
  'انام': 'I sleep',
  'انتبه': 'pay attention / notice!',
  'انترنت': 'Internet',
  'انتظام': 'regularity / consistency',
  'انتهاء': 'End',
  'انتهت': 'ended / finished',
  'انتهى': 'finished / ended',
  'انجازك': 'Your achievement',
  'انجازها': 'Get it done',
  'انجز': 'Accomplished',
  'انحاء': 'All over',
  'انزعجت': 'I was upset',
  'انسان': 'A human being',
  'انشر': 'I publish / post',
  'انصح': 'I advise',
  'انطق': 'pronounce!',
  'انطلق': 'launched / began sprint',
  'انفراج': 'A breakthrough',
  'انني': 'I am',
  'انه': 'He',
  'انهاء': 'Finish',
  'انهي': 'Finish',
  'انيق': 'Elegant',
  'انيقا': 'Elegant',
  'انيقة': 'Elegant',
  'اهمال': 'carelessness / neglect',
  'اوسمة': 'Medals',
  'اوقات': 'Times',
  'اول': 'First',
  'ايما': 'Emma',
  'ب': 'by / with / in (letter Baa)',
  'بإرسال': 'by sending',
  'بإضافة': 'by adding',
  'بإعادة': 'by re-doing / by repeating',
  'باحتراف': 'Professionally',
  'بارك_الله_فيك': 'may Allah bless you!',
  'باستخدام': 'using / by using',
  'باصبعي': 'With my finger',
  'باقة': 'Bouquet',
  'بالابتسامة': 'With a smile',
  'بالاخرين': 'With others',
  'بالاخلاق': 'With morals',
  'بالارجل': 'with feet / legs',
  'بالامور': 'With matters',
  'بالتجارب': 'With experiments',
  'بالجوع': 'With hunger',
  'بالحصاد': 'By harvest',
  'بالدهشة': 'Surprised',
  'بالشيء': 'With something',
  'بالمضرب': 'with the racket / bat',
  'بالياء': 'Curriculum Term',
  'بامتياز': 'Par excellence',
  'بانتباه': 'attentively / with attention',
  'بانتظام': 'regularly / systematically',
  'باني': 'builder / architect',
  'باهر': 'dazzling / brilliant',
  'ببصره': 'With his sight',
  'ببناء': 'By building',
  'بتعليم': 'With education',
  'بتلقي': 'You receive',
  'بثقة': 'With confidence',
  'بجانب': 'beside / next to',
  'بجد': 'Seriously',
  'بجدارة': 'Well deserved',
  'بحر': 'sea',
  'بخصوص': 'regarding / concerning',
  'بخطوة': 'with a step',
  'بدء': 'start',
  'بدأ': 'started / began',
  'بدات': 'It started',
  'بداية': 'start / beginning',
  'بدبي': 'in Dubai',
  'بدل': 'instead of / substitute',
  'بدلاء': 'substitute bench players',
  'بدني': 'physical',
  'بدنية': 'physical / athletic (fem.)',
  'بديل': 'substitute / alternative',
  'برأس': 'with the head / header',
  'برازيل': 'Brazil',
  'برنامجي': 'My program',
  'برونزية': 'bronze',
  'بزيارة': 'By visiting',
  'بسخرية': 'Sarcastically',
  'بسيطة': 'simple / elementary',
  'بصره': 'His sight',
  'بضم': 'with Dammah / by joining',
  'بطاقات': 'cards',
  'بطاقة': 'card (penalty)',
  'بطحن': 'With grinding',
  'بطل': 'champion / hero',
  'بطيء': 'Slow',
  'بعد': 'after / afterwards',
  'بعدما': 'After',
  'بعض': 'some / part of',
  'بعكس': 'unlike / contrary to',
  'بقاع': 'regions / corners (of earth)',
  'بقضاء': 'By spending',
  'بقيت': 'remained / stayed',
  'بك': 'in you / with you',
  'بكتابتي': 'with my writing',
  'بكم': 'How much?',
  'بل': 'Rather',
  'بلا': 'None',
  'بلده': 'His country',
  'بلوم': 'Bloom',
  'بما': 'with what / including',
  'بمتعة': 'With pleasure',
  'بمشاهدة': 'By watching',
  'بمهارة': 'skillfully / with skill',
  'بمهامها': 'With its tasks',
  'بمهامي': 'With my tasks',
  'بن': 'son of (Bin)',
  'بناء': 'Building',
  'بنت': 'girl / daughter',
  'بنجاح': 'successfully',
  'بنسبة': 'at a rate of / by percentage',
  'بنصر': 'ring finger',
  'بنفسك': 'by yourself',
  'بنقطتين': 'Curriculum Term',
  'بنك': 'Bank',
  'بنون': 'Boys',
  'به': 'in him / with it',
  'بها': 'in her / with it',
  'بوابة': 'Portal',
  'بورق': 'With paper',
  'بوضوح': 'clearly',
  'بولو': 'polo',
  'بولينج': 'bowling',
  'بيئة': 'Environment',
  'بيانات': 'Data',
  'بيت': 'house / home',
  'بيتي': 'my home',
  'بيديه': 'with his hands',
  'بيضاء': 'white (fem.)',
  'بيضاوي': 'oval / egg-shaped',
  'بيضاوية': 'oval (fem.)',
  'بيضة': 'egg',
  'بيضوي': 'oval-shaped',
  'بيكاسو': 'Picasso',
  'بين': 'between / explain!',
  'بينما': 'while / whereas',
  'ة': 'Curriculum Term',
  'ت': 'letter Taa / feminine past suffix',
  'تأسيسي': 'foundational',
  'تأمل': 'reflect / ponder!',
  'تأنيث': 'feminine marker (Taa)',
  'تؤجل': 'Postpone',
  'تؤدي': 'lead',
  'تاء': 'Curriculum Term',
  'تاريخ': 'History',
  'تاكيد': 'Confirm',
  'تبدأ': 'she / it begins',
  'تبديل': 'substitution / player change',
  'تبديلات': 'substitutions',
  'تبعث': 'You send',
  'تتجلى': 'manifests / is clearly shown',
  'تتحدث': 'You talk',
  'تتحول': 'It turns',
  'تتدرب': 'You train',
  'تتطابق': 'matches / agrees with',
  'تتطلب': 'requires / demands',
  'تتكون': 'consists of / is composed of',
  'تتميز': 'is characterized / distinguished by',
  'تجارب': 'experiences / experiments',
  'تجاهل': 'Ignore',
  'تجاهله': 'Ignore him',
  'تجب': 'You must',
  'تجربة': 'Experience',
  'تجربتي': 'My experience',
  'تجريبي': 'practice / mock / experimental',
  'تجعلني': 'Make me',
  'تجمعنا': 'unites us / brings us together',
  'تجنب': 'avoiding / avoidance',
  'تحب': 'she loves / likes',
  'تحت': 'under / beneath',
  'تحتاج': 'needs / requires',
  'تحتار': 'hesitate / be confused',
  'تحتسب': 'she awards / calculates',
  'تحتفل': 'You celebrate',
  'تحتوي': 'Contain',
  'تحدث': 'speak!',
  'تحدي': 'challenge',
  'تحديد': 'Determine',
  'تحريك': 'vowelling / adding diacritics',
  'تحريكها': 'vocalizing it with harakat',
  'تحزن': 'You get sad',
  'تحسين': 'Improvement',
  'تحقق': 'verify / achieve',
  'تحقيق': 'achieving / realization',
  'تحكيم': 'refereeing / officiating',
  'تحليل': 'analysis',
  'تحليلها': 'analyzing it',
  'تحميل': 'Download',
  'تحمينا': 'Protect us',
  'تحول': 'transforms / turns into',
  'تحويل': 'Convert',
  'تحية': 'Greetings',
  'تخصيص': 'Customize',
  'تخطئ': 'make a mistake',
  'تخطيط': 'planning',
  'تخلط': 'mix up / confuse',
  'تخلي': 'relinquishing / abandoning',
  'تدخلا': 'Intervention',
  'تدريب': 'training / practice',
  'تدفق': 'flow',
  'تدقيق': 'proofreading / auditing',
  'تدل': 'indicates / points to',
  'تذكر': 'remember / recall!',
  'تذكير': 'masculine form / reminder',
  'تذهب': 'she goes / you go',
  'تراث': 'heritage / legacy',
  'تراثية': 'heritage / traditional (fem.)',
  'تراكيب': 'sentence structures',
  'تربة': 'Soil',
  'تربط': 'Bind',
  'تربية': 'education',
  'ترتيب': 'Arrangement',
  'ترخيص': 'License',
  'ترقيم': 'Numbering',
  'تركض': 'she runs / sprints',
  'ترمي': 'she throws / shoots',
  'تريد': 'want',
  'تزرع': 'You plant',
  'تساعدني': 'Help me',
  'تستخدم': 'uses / utilizes',
  'تستقبل': 'You receive',
  'تسجل': 'she scores / records',
  'تسجيل': 'registration / logging',
  'تسخر': 'Make fun',
  'تسديدة': 'shot / strike',
  'تسع': '9 (nine - fem.)',
  'تسعة': '9 (nine)',
  'تسعون': '90 (ninety)',
  'تسعين': '90 (ninety)',
  'تسلم': 'she receives / is preserved',
  'تسليم': 'Delivery',
  'تسمع': 'she hears / you hear',
  'تسمى': 'is called / named (fem.)',
  'تسمية': 'naming / denomination',
  'تسهم': 'Contribute',
  'تشارك': 'Share',
  'تشبه': 'resembles (fem.)',
  'تشترك': 'participates / joins (fem.)',
  'تشجيع': 'cheering / encouragement',
  'تشكل': 'pose',
  'تشكيل': 'vowelization / diacritics',
  'تصادم': 'collision / clash',
  'تصحيح': 'Correction',
  'تصريف': 'verb conjugation',
  'تصل': 'arrive',
  'تصلك': 'You will receive it',
  'تصميم': 'Design',
  'تصنع': 'You make',
  'تصنيف': 'classification',
  'تضع': 'she puts / places',
  'تطابق': 'concord / agreement',
  'تطبيق': 'application / practice',
  'تظهر': 'appear',
  'تعاون': 'cooperation / teamwork',
  'تعبير': 'expression / written composition',
  'تعتمد': 'relies / depends on',
  'تعجب': 'He wondered',
  'تعد': 'is counted / considered',
  'تعديل': 'Edit',
  'تعذر': 'Unable to',
  'تعرض': 'exposed',
  'تعرفه': 'you know it',
  'تعريف': 'definition',
  'تعطي': 'she gives',
  'تعكس': 'reflects',
  'تعلم': 'learned',
  'تعلمت': 'I learned / you learned',
  'تعلمتها': 'I learned it',
  'تعليق': 'Comment',
  'تعليقاتكم': 'Your comments',
  'تعليمات': 'Instructions',
  'تعليمية': 'educational / instructional',
  'تعميق': 'Deepen',
  'تغيير': 'change / substitution',
  'تفاعلي': 'Interactive',
  'تفرق': 'distinguish / differentiate',
  'تفسير': 'Interpretation',
  'تفصيلية': 'detailed',
  'تفضل': 'you prefer / please',
  'تفضيل': 'preference / superlative',
  'تفعل': 'she does / you do',
  'تفعيل': 'Activate',
  'تفكك': 'Break up',
  'تفكير': 'thinking / thought',
  'تفوق': 'excellence / superiority',
  'تقابلك': 'you encounter / face',
  'تقاليد': 'traditions / customs',
  'تقدما': 'Progress',
  'تقدمي': 'Progressive',
  'تقديم': 'delivering / presentation',
  'تقديمي': 'presentation / introductory',
  'تقرأ': 'she reads',
  'تقرير': 'Report',
  'تقع': 'is located / falls',
  'تقليدية': 'traditional',
  'تقليص': 'shrink',
  'تقول': 'she says / you say',
  'تقوم': 'carries out (fem.)',
  'تقوي': 'Strengthen',
  'تقوية': 'strengthening / fortifying',
  'تقويمية': 'formative / diagnostic',
  'تقييم': 'Evaluation',
  'تكتب': 'she writes / you write',
  'تكتيكية': 'tactical',
  'تكسير': 'broken plural',
  'تكنولوجيا': 'technology',
  'تكون': 'Be',
  'تلبس': 'You wear',
  'تلعب': 'she plays / you play',
  'تلفاز': 'television / TV',
  'تلقائي': 'Auto',
  'تلقائيا': 'Automatically',
  'تلقب': 'is nicknamed',
  'تلك': 'that (feminine)',
  'تلميح': 'hint / pedagogical clue',
  'تم': 'completed / was done',
  'تماثيل': 'Statues',
  'تمارين': 'Exercises',
  'تماس': 'touchline / throw-in line',
  'تماما': 'completely / exactly',
  'تمت': 'Done',
  'تمثال': 'Statue',
  'تمثالا': 'A statue',
  'تمثل': 'represents / exemplifies',
  'تمر': 'dates',
  'تمرير': 'passing / pass',
  'تمريرة': 'a pass',
  'تمنيت': 'I wished',
  'تميز': 'distinguish / excel',
  'تنتهي': 'it ends / finishes',
  'تنس': 'tennis',
  'تنطق': 'is pronounced / articulated',
  'تنظيف': 'Cleaning',
  'تنغيم': 'intonation',
  'تنقسم': 'is divided / splits into',
  'تنقيح': 'editing / proofreading',
  'تنمية': 'Development',
  'تنوين': 'Tanween (nunation)',
  'توارثه': 'Inherited',
  'توجد': 'there is / exists (fem.)',
  'توجيهيا': 'Guidance',
  'تود': 'would like / wish',
  'توسع': 'Expansion',
  'توضيح': 'Clarification',
  'توعية': 'Awareness',
  'توقف': 'stoppage / halt',
  'توقيت': 'timing / schedule',
  'ثانية': 'second',
  'ثبتت': 'was proven / confirmed',
  'ثقافة': 'Culture',
  'ثقيلة': 'heavy',
  'ثلاث': '3 (three - fem.)',
  'ثلاثة': '3 (three)',
  'ثلاثون': '30 (thirty)',
  'ثلاثين': '30 (thirty)',
  'ثم': 'then',
  'ثمان': '8 (eight - fem.)',
  'ثمانون': '80 (eighty)',
  'ثمانية': '8 (eight)',
  'ثمانين': '80 (eighty)',
  'ثنائية': 'dual / paired',
  'ثوان': 'seconds',
  'ثوب': 'dress / robe / garment',
  'ج': 'C (choice C)',
  'جاء': 'came',
  'جائزة': 'prize / award',
  'جائزته': 'His reward',
  'جاد': 'Serious',
  'جاذبة': 'attractive / charming',
  'جار': 'ongoing / in progress / neighbor',
  'جارفة': 'overwhelming / immense',
  'جاري': 'ongoing / in progress / current',
  'جاك': 'Jack',
  'جاهز': 'Ready',
  'جاهزية': 'Readiness',
  'جد': 'grandfather',
  'جدا': 'very',
  'جدة': 'grandmother',
  'جدول': 'Schedule',
  'جدي': 'Seriously',
  'جديد': 'new (masc.)',
  'جديدة': 'new (fem.)',
  'جذبت': 'attracted / captivated',
  'جر': 'genitive case / preposition',
  'جرب': 'try / test!',
  'جرس': 'bell',
  'جرعات': 'doses',
  'جري': 'running',
  'جزاء': 'penalty / penalty area',
  'جسم': 'body',
  'جلد': 'leather',
  'جلسات': 'Sessions',
  'جلسة': 'session / study session',
  'جماعي': 'team / collective',
  'جماعية': 'team / collective (fem.)',
  'جمال': 'beauty / splendor',
  'جمالها': 'its beauty',
  'جماهير': 'spectators',
  'جمع': 'plural',
  'جمل': 'sentences',
  'جملة': 'sentence',
  'جميع': 'all / everyone',
  'جميل': 'beautiful',
  'جميلة': 'beautiful (fem.)',
  'جنوب': 'south',
  'جهاز': 'device / tablet / apparatus',
  'جهودكم': 'Your efforts',
  'جوائز': 'prizes / awards',
  'جواب': 'answer',
  'جولة': 'Tour',
  'جولف': 'golf',
  'جون': 'John',
  'جوهري': 'fundamental / core',
  'جيد': 'good / well',
  'جيدة': 'good (fem.)',
  'جيل': 'Generation',
  'جيلا': 'Generation',
  'ح': 'letter Haa',
  'حاجز': 'Barrier',
  'حارس': 'goalkeeper',
  'حافر': 'hoof',
  'حافظ': 'preserve / guard!',
  'حال': 'Status',
  'حالك': 'How are you?',
  'حاليا': 'Currently',
  'حاملا': 'the two linesmen carrying',
  'حاملو': 'carriers / holders',
  'حاول': 'Try',
  'حب': 'Love',
  'حبة': 'grain / pill / seed',
  'حبه': 'His love',
  'حبي': 'My love',
  'حجم': 'size / volume',
  'حدث': 'It happened',
  'حدد': 'specify / determine!',
  'حديثا': 'speech / discourse',
  'حديثة': 'modern / recent',
  'حديقة': 'garden',
  'حذاء': 'shoe',
  'حذف': 'deletion / omission',
  'حراسة': 'goalkeeping / guarding',
  'حرف': 'particle / letter',
  'حرك': 'vowel / move!',
  'حركة': 'vowel mark / movement',
  'حروف': 'letters / particles',
  'حرير': 'silk',
  'حزام': 'Belt',
  'حزينا': 'Sad',
  'حساب': 'account / calculation',
  'حسابي': 'my profile / account',
  'حسب': 'according to / depending on',
  'حسن': 'Good',
  'حصاد': 'Harvest',
  'حصان': 'horse / stallion',
  'حصلت': 'I got',
  'حصوله': 'It happens',
  'حضر': 'attended / came',
  'حفظ': 'Save',
  'حق': 'Right',
  'حقوق': 'rights / laws',
  'حقوقي': 'my rights',
  'حقيبة': 'bag / backpack',
  'حقيقي': 'Real',
  'حكام': 'referees',
  'حكايات': 'Tales',
  'حكم': 'referee / judge',
  'حكيم': 'Wise',
  'حل': 'Solution',
  'حلل': 'analyze!',
  'حليب': 'milk',
  'حماس': 'enthusiasm / excitement',
  'حماسها': 'its enthusiasm',
  'حمدان': 'Hamdan',
  'حمراء': 'red',
  'حمل': 'carried',
  'حواجز': 'hurdles / barriers',
  'حوار': 'Dialogue',
  'حوافر': 'hooves',
  'حوالي': 'approximately / around',
  'حوض': 'pool / basin',
  'حول': 'around',
  'حي': 'neighborhood / living',
  'حياتنا': 'Our lives',
  'حيث': 'where / since',
  'خائفا': 'Scared',
  'خارج': 'outside',
  'خاص': 'special / private',
  'خاطئة': 'incorrect (fem.)',
  'خالية': 'Empty',
  'خامات': 'raw materials',
  'خامس': 'fifth',
  'خبر': 'predicate (news/info of nominal sentence)',
  'خبز': 'bread',
  'خبير': 'expert',
  'خروج': 'exit / coming off',
  'خريف': 'autumn',
  'خسارة': 'loss / defeat',
  'خسر': 'lost',
  'خصال': 'traits / virtues',
  'خصوصي': 'private / tutoring',
  'خضار': 'vegetables',
  'خضراء': 'green (fem.)',
  'خضروات': 'vegetables',
  'خط': 'line',
  'خطأ': 'foul / mistake',
  'خطاط': 'calligrapher',
  'خطة': 'study plan',
  'خطر': 'Danger',
  'خطوات': 'Steps',
  'خطوة': 'step',
  'خطي': 'calligraphic / linear',
  'خفيف': 'light / agile',
  'خلف': 'behind',
  'خللا': 'A glitch',
  'خلو': 'Empty',
  'خمس': '5 (five - fem.)',
  'خمسة': '5 (five)',
  'خمسون': '50 (fifty)',
  'خمسين': '50 (fifty)',
  'خنصر': 'pinky / little finger',
  'خوض': 'wade',
  'خيالية': 'fictional / fantasy',
  'خيل': 'horses / cavalry',
  'د': 'D (choice D)',
  'دائرة': 'circle',
  'دائما': 'always',
  'داخل': 'inside / within',
  'داعم': 'Supportive',
  'داعمة': 'Supportive',
  'دافنشي': 'Da Vinci',
  'دبي': 'Dubai',
  'دجاج': 'chicken',
  'دخول': 'entry / coming on',
  'دراسات': 'studies',
  'دراسة': 'study',
  'دراسي': 'academic / scholastic',
  'درجات': 'Degrees',
  'درجة': 'degree / mark / grade',
  'درس': 'lesson',
  'دروس': 'lessons / units',
  'دروسي': 'My lessons',
  'دفتر': 'notebook',
  'دقائق': 'minutes',
  'دقة': 'accuracy / precision',
  'دقيق': 'precise / exact',
  'دقيقة': 'minute',
  'دليل': 'guide / handbook / proof',
  'دور': 'Turn',
  'دولار': 'Dollar',
  'دولة': 'country / state',
  'دولي': 'international',
  'دون': 'without',
  'ذاتي': 'self / individual',
  'ذاتية': 'individual / personal (fem.)',
  'ذكي': 'smart / intelligent',
  'ذكية': 'smart / intelligent (fem.)',
  'ذلك': 'that (masculine)',
  'ذهب': 'went',
  'ذهبت': 'I went',
  'ذهبية': 'gold / golden',
  'ذوو': 'possessors of / people with',
  'ذوي': 'With',
  'ذين': 'who (dual)',
  'ر': 'letter Raa',
  'رأى': 'saw',
  'رؤية': 'vision',
  'رئيسة': 'main / principal',
  'رئيسيين': 'primary / main (players)',
  'رائع': 'wonderful / excellent',
  'رائعة': 'wonderful (fem.)',
  'رابع': 'fourth',
  'رابعة': 'fourth (fem.)',
  'راجع': 'See',
  'راشد': 'Rashid (proper name)',
  'راية': 'flag / banner',
  'رايت': 'Wright',
  'ربط': 'Connect',
  'ربيع': 'spring',
  'رتب': 'arranged / organized',
  'رجبي': 'rugby',
  'رجع': 'returned',
  'رحلة': 'trip / journey',
  'رد': 'Reply',
  'رسائل': 'Messages',
  'رسالة': 'letter / message',
  'رسالتك': 'Your message',
  'رسالتي': 'My message',
  'رسام': 'painter / artist',
  'رسم': 'drawing / painting',
  'رسمي': 'official',
  'رسمية': 'official (fem.)',
  'رصيد': 'balance / wallet points',
  'رغبتك': 'Your desire',
  'رغم': 'despite / although',
  'رفعه': 'its raising / nominative mark',
  'رفيعة': 'Thin',
  'رفيق': 'companion / friend',
  'رفيقك': 'your companion / guide',
  'رقم': 'number / figure',
  'ركائز': 'Pillars',
  'ركبي': 'rugby',
  'ركض': 'sprinting / running',
  'ركضن': 'They ran',
  'ركضوا': 'They ran',
  'ركل': 'kicking',
  'ركلات': 'kicks / penalty kicks',
  'ركلة': 'kick',
  'ركوب': 'riding',
  'ركيزة': 'pillar',
  'رماية': 'archery / shooting',
  'رمز': 'Symbol',
  'رمزا': 'Symbol',
  'رمل': 'sand',
  'رمي': 'Throw',
  'روح': 'spirit',
  'روعة': 'magnificence / wonder',
  'رياضات': 'sports',
  'رياضة': 'sport / exercise',
  'رياضتان': 'two sports',
  'رياضتك': 'your sport',
  'رياضته': 'his sport',
  'رياضتها': 'her sport',
  'رياضتي': 'my sport',
  'رياضي': 'sporty / athletic / athlete',
  'رياضيات': 'mathematics',
  'ريان': 'Ryan',
  'زايد': 'Zayed (late Sheikh Zayed, founding father of UAE)',
  'زرت': 'I visited',
  'زرقاء': 'blue (fem.)',
  'زرنا': 'We visited',
  'زملاء': 'classmates',
  'زملائك': 'Your colleagues',
  'زملائي': 'my classmates / peers',
  'زميل': 'classmate / peer',
  'زي': 'Costume',
  'زيا': 'Zia',
  'زيادة': 'increase / addition',
  'زينت': 'Decorated',
  'زيه': 'Like him',
  'زيها': 'Her outfit',
  'س': 'future particle (will)',
  'سأل': 'asked',
  'سؤال': 'question',
  'سؤالك': 'your question',
  'ساحة': 'pitch / arena / court',
  'ساحرة': 'magician / charming (fem.)',
  'ساذهب': 'I\\',
  'سارة': 'Sarah',
  'سارت': 'walked / proceeded',
  'سازور': 'I will visit',
  'ساشارك': 'I will participate',
  'ساشتري': 'I will buy',
  'ساعات': 'hours',
  'ساعة': 'hour / clock',
  'ساعد': 'helped',
  'ساقين': 'two shins / two legs',
  'سالم': 'sound plural',
  'ساهم': 'contributed',
  'سبابة': 'index finger',
  'سباح': 'Swimmer',
  'سباحة': 'swimming',
  'سباق': 'race / competition',
  'سبب': 'reason / cause',
  'سبت': 'Saturday',
  'سبع': '7 (seven - fem.)',
  'سبعة': '7 (seven)',
  'سبعون': '70 (seventy)',
  'سبعين': '70 (seventy)',
  'سبورة': 'blackboard / whiteboard',
  'ست': '6 (six - fem.)',
  'ستة': '6 (six)',
  'ستشتري': 'You will buy',
  'ستصل': 'you will reach / arrive',
  'ستكون': 'will be (fem.)',
  'ستون': '60 (sixty)',
  'ستين': '60 (sixty)',
  'سجل': 'scored / registered',
  'سجلت': 'she scored / recorded',
  'سحر': 'magic / charm',
  'سحرت': 'captivated / enchanted',
  'سحرها': 'its charm / magic',
  'سحري': 'magical',
  'سحق': 'crushing / overpowering',
  'سخرية': 'Sarcasm',
  'سد': 'Dam',
  'سدد': 'shot / kicked the ball',
  'سر': 'Secret',
  'سرج': 'saddle',
  'سرد': 'narration / recounting',
  'سرعة': 'speed',
  'سروال': 'pants / trousers',
  'سريري': 'My bed',
  'سريع': 'fast / quick',
  'سعر': 'Price',
  'سعيد': 'happy (masc.)',
  'سعيدة': 'happy (fem.)',
  'سفاري': 'safari (Desert Safari)',
  'سقراطي': 'Socratic (dialogue)',
  'سقطت': 'fell / dropped',
  'سقوط': 'fall / collapse',
  'سكون': 'Curriculum Term',
  'سلة': 'basket',
  'سلطان': 'Sultan',
  'سلوك': 'Behavior',
  'سليم': 'sound / correct / healthy',
  'سم': 'cm (centimeter)',
  'سمة': 'trait / characteristic',
  'سمع': 'heard',
  'سمعت': 'I heard',
  'سمك': 'fish',
  'سمي': 'was named / dubbed',
  'سميت': 'was named / dubbed (fem.)',
  'سمير': 'Samir',
  'سنابل': 'Sanabel',
  'سنة': 'year',
  'سنتيمترا': 'centimeters (accusative)',
  'سنتين': 'two years',
  'سنحتفل': 'We will celebrate',
  'سنفكر': 'We will think',
  'سنوات': 'years',
  'سهل': 'easy',
  'سهلة': 'easy (fem.)',
  'سهولة': 'ease / facility',
  'سهيل': 'Suhail',
  'سوداء': 'black (fem.)',
  'سوزان': 'Susan',
  'سيء': 'Bad',
  'سياق': 'context',
  'سيتم': 'It will be done',
  'سيلعب': 'he will play',
  'ش': 'letter Sheen',
  'شأن': 'matter / importance',
  'شائعة': 'common',
  'شارك': 'participated',
  'شاركت': 'I shared',
  'شاركن': 'Share',
  'شاركوا': 'Share',
  'شاطئ': 'beach / coast',
  'شاملة': 'comprehensive (fem.)',
  'شاهد': 'watched / saw',
  'شباك': 'net / goal nets',
  'شبكة': 'network',
  'شبه': 'semi- / resemblance',
  'شتاء': 'winter',
  'شتى': 'various / diverse',
  'شجاع': 'brave / courageous',
  'شجاعة': 'courage / bravery',
  'شخص': 'person',
  'شد': 'pull / tighten',
  'شدة': 'Shaddah (gemination mark)',
  'شراء': 'Buy',
  'شرب': 'drank',
  'شرح': 'explanation',
  'شرحك': 'your explanation',
  'شرق': 'east',
  'شروط': 'rules / conditions / criteria',
  'شريط': 'bar',
  'شعبية': 'popularity / popular (fem.)',
  'شعر': 'Poetry',
  'شفاف': 'Transparent',
  'شكرا': 'thank you',
  'شكل': 'shape / form',
  'شمال': 'north / left',
  'شمس': 'sun',
  'شملت': 'included / encompassed',
  'شهد': 'He witnessed',
  'شهر': 'month',
  'شهير': 'famous / renowned',
  'شوط': 'half / round',
  'شوطين': 'two halves',
  'شوقي': 'My longing',
  'شيء': 'thing / something',
  'شيئا': 'anything / something',
  'شيئين': 'Two things',
  'شيلة': 'Shayla (headscarf)',
  'شيوعا': 'Common',
  'ص': 'Curriculum Term',
  'صاحب': 'owner / holder',
  'صار': 'became',
  'صافية': 'Clear',
  'صالات': 'indoor halls / futsal arena',
  'صالة': 'gym / sports hall',
  'صالح': 'valid / righteous',
  'صباح': 'morning',
  'صباحا': 'in the morning',
  'صبر': 'patience / endurance',
  'صحة': 'health',
  'صحح': 'correct! / rectify',
  'صحراء': 'desert',
  'صحي': 'healthy',
  'صحيح': 'correct / true',
  'صحيحة': 'correct (fem.)',
  'صديق': 'friend (male)',
  'صديقة': 'friend (female)',
  'صراحة': 'Honestly',
  'صرف': 'morphology / pure',
  'صعب': 'difficult / hard',
  'صعبة': 'difficult (fem.)',
  'صعوبة': 'difficulty / hardship',
  'صغاري': 'My little ones',
  'صغير': 'small / young',
  'صف': 'class / grade',
  'صفارة': 'referee whistle',
  'صفحات': 'Pages',
  'صفحة': 'page',
  'صفر': '0 (zero)',
  'صفراء': 'yellow',
  'صفي': 'Describe',
  'صقارة': 'falconry',
  'صقر': 'falcon',
  'صممت': 'Designed',
  'صناعة': 'Industry',
  'صنع': 'Made',
  'صنف': 'classify / categorize!',
  'صوت': 'sound / phoneme',
  'صوته': 'its sound / phoneme',
  'صور': 'Pictures',
  'صورة': 'Image',
  'صوف': 'wool',
  'صيد': 'hunting',
  'صيغة': 'Formula',
  'صيف': 'summer',
  'ض': 'letter Dhad',
  'ضائع': 'added / stoppage time',
  'ضحك': 'laughter / laughing',
  'ضد': 'against / versus',
  'ضرب': 'striking / hitting',
  'ضربة': 'kick / strike',
  'ضريبة': 'Tax',
  'ضريبية': 'Tax',
  'ضع': 'put! / place!',
  'ضمائر': 'pronouns',
  'ضمة': 'Curriculum Term',
  'ضمن': 'within / among',
  'ضمه': 'its Dammah',
  'ضمير': 'Conscience',
  'ضوئي': 'optical / visual',
  'ط': 'letter Taa',
  'طائرة': 'volleyball / plane',
  'طابقت': 'I matched',
  'طابور': 'morning line-up / queue',
  'طاقة': 'energy',
  'طاقم': 'crew / officiating team',
  'طالب': 'student (male)',
  'طالبة': 'student (female)',
  'طالما': 'as long as',
  'طباعة': 'Print',
  'طبعة': 'Edition',
  'طبق': 'apply! / practiced',
  'طبيعي': 'natural / normal',
  'طحن': 'Grinding',
  'طحين': 'Flour',
  'طرح': 'subtraction / posing (question)',
  'طرد': 'send-off / red card',
  'طريق': 'path / way',
  'طريقة': 'method / manner',
  'طعام': 'food',
  'طعامي': 'my food',
  'طلاب': 'students',
  'طلاقة': 'fluency',
  'طلباتي': 'My requests',
  'طموحي': 'My ambition',
  'طوال': 'Throughout',
  'طور': 'developed',
  'طول': 'length',
  'طولية': 'longitudinal',
  'طويل': 'long / tall',
  'طيبة': 'Good',
  'ظ': 'letter Zhaa',
  'ظاهر': 'apparent / manifest',
  'ظاهرة': 'apparent mark / phenomenon',
  'ظهر': 'Noon',
  'ع': 'letter Ain',
  'عائلة': 'family',
  'عاد': 'returned',
  'عاقل': 'rational / human (animate noun)',
  'عال': 'High',
  'عالم': 'world',
  'عالميا': 'globally / worldwide',
  'عام': 'year / general',
  'عباءة': 'Abaya (Emirati women robe)',
  'عبارة': 'phrase / expression',
  'عبر': 'across / through',
  'عجب': 'wonder / amazement',
  'عد': 'count / consider!',
  'عدا': 'except / apart from',
  'عداء': 'runner / sprinter',
  'عدالة': 'fairness / justice',
  'عدة': 'several / multiple',
  'عدد': 'number / count',
  'عدم': 'Not',
  'عديدة': 'numerous / many',
  'عذبة': 'Fresh',
  'عذرا': 'Sorry',
  'عربي': 'Arab / Arabic',
  'عربية': 'Arabic (fem.)',
  'عرض': 'width',
  'عرضية': 'lateral / crossbar',
  'عرف': 'knew / recognized',
  'عرفت': 'knew / recognized',
  'عريق': 'Ancient',
  'عريقة': 'ancient / deep-rooted',
  'عش': 'live!',
  'عشاء': 'dinner',
  'عشاقها': 'its enthusiasts / lovers',
  'عشب': 'grass / turf',
  'عشبي': 'grassy (pitch)',
  'عشت': 'lived',
  'عشر': '10 (ten - fem.)',
  'عشرة': '10 (ten)',
  'عشرون': '20 (twenty)',
  'عشرين': '20 (twenty)',
  'عشنا': 'We lived',
  'عصر': 'era / time',
  'عصير': 'juice',
  'عضلات': 'muscles',
  'عطلة': 'holiday / vacation',
  'عفوا': 'you are welcome / pardon',
  'عقال': 'Egal (headband)',
  'عقل': 'mind / intellect',
  'عقله': 'his mind',
  'عقول': 'minds / intellects',
  'عقولهم': 'their minds',
  'عكس': 'Reverse',
  'علاج': 'Treatment',
  'علامة': 'inflection mark / sign',
  'علل': 'give reason / explain why!',
  'علم': 'taught / knew',
  'علمت': 'I knew',
  'علوم': 'sciences',
  'على': 'on / upon',
  'عليك': 'upon you / you should',
  'علينا': 'upon us / we should',
  'عم': 'Uncle',
  'عمره': 'his age',
  'عمل': 'work / action',
  'عملك': 'your work',
  'عميق': 'deep / profound',
  'عن': 'about / away from',
  'عناصر': 'Elements',
  'عناية': 'care / attention',
  'عند': 'at / when / with',
  'عندما': 'when / while',
  'عنف': 'violence / rough play',
  'عنوان': 'title / address',
  'عودتها': 'Her return',
  'عودتهم': 'Their return',
  'عين': 'eye / fountain / Al Ain city',
  'غ': 'letter Ghain',
  'غارقا': 'Drenched',
  'غالبا': 'often / mostly',
  'غترة': 'Ghutrah (headdress)',
  'غدا': 'tomorrow',
  'غداء': 'lunch',
  'غراما': 'grams',
  'غرب': 'west',
  'غرس': 'Plant',
  'غرف': 'rooms',
  'غرفة': 'room',
  'غطاه': 'Cover it',
  'غلاف': 'Cover',
  'غير': 'non- / other than',
  'ف': 'so / then (conjunction)',
  'فإن': 'indeed / then',
  'فائدة': 'benefit / takeaway',
  'فاتناول': 'So eat',
  'فاتنة': 'fascinating / captivating',
  'فاتورة': 'invoice',
  'فارس': 'knight / equestrian rider',
  'فاز': 'won',
  'فازت': 'she won',
  'فازوا': 'they won',
  'فاضل': 'distinguished / virtuous',
  'فاطمة': 'Fatima (proper name)',
  'فاعل': 'subject (doer of the verb)',
  'فاكهة': 'fruit',
  'فتح': 'opened',
  'فتحة': 'Fathah mark',
  'فتحته': 'its Fathah',
  'فترات': 'periods / intervals',
  'فترة': 'period / interval',
  'فتعلمت': 'So I learned',
  'فتكتب': 'so it is written',
  'فتكون': 'so it becomes',
  'فجأة': 'suddenly',
  'فجوات': 'Gaps',
  'فجوة': 'gap',
  'فخاخ': 'Traps',
  'فخر': 'pride',
  'فخرا': 'pride (accusative)',
  'فراغ': 'blank space',
  'فرح': 'happiness / joy',
  'فرد': 'individual / person',
  'فردي': 'individual / solo',
  'فردية': 'individual / solo (fem.)',
  'فرس': 'mare / horse',
  'فرشاة': 'brush',
  'فرعية': 'secondary / branch (mark)',
  'فرق': 'distinguish / differences',
  'فروسية': 'equestrianism / horsemanship',
  'فريق': 'team',
  'فريقان': 'two teams',
  'فريقين': 'two teams',
  'فزت': 'I won',
  'فسر': 'interpret / explain!',
  'فصل': 'chapter / classroom / term',
  'فصلية': 'term-based / quarterly',
  'فصول': 'Chapters',
  'فضل': 'preferred',
  'فضلت': 'preferred',
  'فضي': 'Silver',
  'فضية': 'silver',
  'فعل': 'verb',
  'فعلت': 'I did',
  'فعلية': 'verbal (sentence starting with verb)',
  'فقد': 'has already / lost',
  'فقرة': 'paragraph / passage',
  'فقط': 'only',
  'فكر': 'think / reflect!',
  'فلا': 'so do not',
  'فلبست': 'So I got dressed',
  'فما': 'so what',
  'فن': 'art',
  'فنان': 'artist',
  'فنكتب': 'so we write',
  'فنون': 'arts',
  'فهرس': 'Index',
  'فهم': 'understood',
  'فهما': 'understanding',
  'فهمت': 'understood',
  'فهمك': 'your understanding',
  'فهو': 'so he / so it is',
  'فهي': 'so she / so it is',
  'فاهم': 'understanding / intelligent / Fahim',
  'فهيم': 'understanding / perceptive / intelligent',
  'فوائد': 'benefits / advantages',
  'فواكه': 'fruits',
  'فوري': 'Immediate',
  'فوز': 'victory / winning',
  'فوق': 'above / over',
  'في': 'in / at',
  'فيتراوح': 'so it ranges',
  'فيفا': 'FIFA',
  'فيلم': 'movie',
  'فيه': 'in it / therein',
  'فيها': 'in it / therein',
  'فيهما': 'in both of them',
  'ق': 'letter Qaaf',
  'قائد': 'captain / leader',
  'قائلا': 'Saying',
  'قائمة': 'list / menu',
  'قاد': 'led / captained',
  'قادة': 'leaders / captains',
  'قارئ': 'reader',
  'قارب': 'approached / boat',
  'قارن': 'compare!',
  'قاعة': 'hall / court',
  'قاعدة': 'rule / foundation',
  'قال': 'said',
  'قالت': 'She said',
  'قام': 'performed / stood',
  'قامت': 'undertook / stood',
  'قاموس': 'glossary / dictionary',
  'قاموسي': 'my glossary / my dictionary',
  'قانون': 'law / regulation',
  'قانوني': 'legal / official',
  'قانونية': 'legal / official (fem.)',
  'قاهر': 'conqueror / overwhelming',
  'قبعة': 'hat / cap',
  'قبل': 'before / prior to',
  'قبلها': 'before it',
  'قبيل': 'shortly before / type',
  'قد': 'may / certainly / already',
  'قدر': 'amount / extent',
  'قدرتك': 'your ability',
  'قدم': 'foot',
  'قدمت': 'presented / stepped forward',
  'قديم': 'old / ancient',
  'قديمة': 'old / traditional (fem.)',
  'قرأ': 'read',
  'قرأته': 'I read it',
  'قراءة': 'reading',
  'قراءته': 'reading it',
  'قرات': 'I read',
  'قرب': 'near',
  'قرر': 'Decide',
  'قررت': 'I decided',
  'قريب': 'near / close',
  'قسط': 'Premium',
  'قسم': 'section / divide!',
  'قسيمة': 'Coupon',
  'قصة': 'story',
  'قصص': 'stories',
  'قصير': 'short',
  'قصيرة': 'short (fem.)',
  'قضاء': 'Judiciary',
  'قضى': 'spent (time)',
  'قضيت': 'I spent',
  'قط': 'ever / never',
  'قطار': 'Train',
  'قطع': 'cutting / disjunction',
  'قطن': 'cotton',
  'قفز': 'jumping',
  'قل': 'say!',
  'قلب': 'heart',
  'قلم': 'pen / pencil',
  'قلماء': 'Qalama',
  'قلوب': 'hearts',
  'قليل': 'few / little',
  'قليلا': 'a little / briefly',
  'قليلة': 'few / little (fem.)',
  'قمة': 'peak / summit',
  'قمت': 'I performed / stood',
  'قمح': 'wheat',
  'قميص': 'shirt',
  'قواعد': 'rules / foundations',
  'قوانين': 'rules / laws',
  'قوانينها': 'its rules / regulations',
  'قوة': 'power / strength',
  'قوى': 'athletics / track and field',
  'قوي': 'strong / powerful',
  'قوية': 'strong (fem.)',
  'قياس': 'measurement / standard',
  'قياسي': 'record / benchmark',
  'قياسية': 'record-breaking (fem.)',
  'قيد': 'under / in process of',
  'قيم': 'values / morals',
  'ك': 'like / as (preposition)',
  'كأس': 'trophy / cup',
  'كأنه': 'as if he',
  'كابتن': 'captain / skipper',
  'كاتب': 'author / writer',
  'كارلوس': 'Carlos',
  'كافة': 'all / entire',
  'كامل': 'complete / full',
  'كاملا': 'completely / fully',
  'كاملة': 'complete / full',
  'كان': 'was',
  'كانت': 'she / it was',
  'كانوا': 'they were',
  'كبد': 'toil / endure hardships',
  'كبسولات': 'capsules (micro-lessons)',
  'كبسولة': 'capsule (micro-lesson)',
  'كبير': 'large / big',
  'كبيرة': 'large / big (fem.)',
  'كتاب': 'book',
  'كتابة': 'writing / composition',
  'كتابتي': 'my writing',
  'كتابن': 'My book',
  'كتب': 'wrote',
  'كتبت': 'I wrote / was written',
  'كثير': 'many / much',
  'كثيرا': 'a lot / frequently',
  'كثيرة': 'many / much (fem.)',
  'كذلك': 'likewise / also',
  'كرات': 'balls',
  'كرة': 'ball',
  'كرتك': 'your ball',
  'كرته': 'his ball',
  'كرتها': 'her ball',
  'كرتي': 'my ball',
  'كرسي': 'chair / seat',
  'كرم': 'honored / generosity',
  'كريكت': 'cricket',
  'كسر': 'breaking / fraction',
  'كسرة': 'Kasrah mark',
  'كسرته': 'its Kasrah',
  'كشف': 'revealing / detection',
  'كفريق': 'as a team',
  'كل': 'all / every / each',
  'كلا': 'nay / absolutely not',
  'كلاعب': 'as a player',
  'كلام': 'speech / talk',
  'كلمة': 'word',
  'كلنا': 'All of us',
  'كله': 'All of it',
  'كلها': 'all of it',
  'كلهم': 'all of them',
  'كلي': 'overall / total / complete',
  'كم': 'how many / how much',
  'كما': 'just as / also',
  'كمثال': 'as an example',
  'كن': 'be!',
  'كنت': 'I was / you were',
  'كندورة': 'Kandura (Emirati traditional robe)',
  'كيدن': 'Kidden',
  'كيف': 'how',
  'كيفية': 'method / how to',
  'ل': 'for / to (preposition)',
  'لأساعدك': 'to assist you',
  'لأن': 'because',
  'لأنه': 'because he / it',
  'لأنها': 'because she / it',
  'لأنهم': 'because they',
  'لإدارة': 'to officiate / manage',
  'لا': 'no / not',
  'لابد': 'Must',
  'لاحظ': 'observe / note!',
  'لازم': 'necessary / intransitive',
  'لاصدقائي': 'To my friends',
  'لاظهار': 'To show',
  'لاعب': 'player',
  'لاعبا': 'players (accusative count)',
  'لاعبات': 'female players',
  'لاعباً': 'players (accusative count)',
  'لاعبة': 'female player',
  'لاعبون': 'players (nominative)',
  'لاعبين': 'players',
  'لاعرف': 'to know / in order to find out',
  'لاكمال': 'To complete',
  'لانني': 'Because I am',
  'لانها': 'because she / because it',
  'لبدء': 'To start',
  'لتبني': 'To build',
  'لتحقيق': 'to achieve / attain',
  'لتطوير': 'To develop',
  'لتعزيز': 'To enhance',
  'لتعلم': 'for learning / to learn',
  'لتكتشف': 'so you discover',
  'لتكون': 'To be',
  'لتناسب': 'To fit',
  'لجام': 'bridle / reins',
  'لجدي': 'For my grandfather',
  'لجذبها': 'to attract it',
  'لحظات': 'moments',
  'لحم': 'meat',
  'لديك': 'you have',
  'لدينا': 'we have',
  'لذا': 'therefore / so',
  'لذلك': 'therefore / for that reason',
  'لذيذ': 'delicious / tasty',
  'لرمي': 'for shooting / throwing',
  'لزم': 'was required',
  'لسان': 'tongue / language',
  'لسنوات': 'for years',
  'لشراء': 'To buy',
  'لضمان': 'To guarantee',
  'لطحنه': 'To grind it',
  'لطيف': 'kind / pleasant',
  'لعب': 'playing / to play',
  'لعبة': 'game / sport',
  'لعبت': 'she played',
  'لعبتم': 'You played',
  'لعبوا': 'they played',
  'لعل': 'perhaps / hopefully',
  'لغة': 'language',
  'لغوي': 'linguistic / language',
  'لفن': 'For art',
  'لقب': 'was nicknamed',
  'لقبت': 'was nicknamed',
  'لقبها': 'its nickname / title',
  'لقد': 'indeed / already',
  'لك': 'for you',
  'لكل': 'for each / every',
  'لكم': 'for you (plural)',
  'لكن': 'but / however',
  'لكنني': 'But I am',
  'لكنه': 'but he',
  'لكنها': 'but she',
  'لكي': 'in order to',
  'للاشتراك': 'To subscribe',
  'للاطفال': 'For children',
  'للامتنان': 'For gratitude',
  'للانضباط': 'For discipline',
  'للايقاف': 'To stop',
  'للبدء': 'To start',
  'للتاكد': 'To confirm',
  'للتخطيط': 'for planning',
  'للترفيه': 'For entertainment',
  'للتعليم': 'For education',
  'للتمييز': 'to distinguish',
  'للتنافس': 'To compete',
  'للحصاد': 'To harvest',
  'للرجال': 'For men',
  'للرغبة': 'For desire',
  'للزراعة': 'For agriculture',
  'للساكن': 'for the unvowelled sukun consonant',
  'للسيدة': 'For the lady',
  'للغائب': 'For the absent',
  'للفضاء': 'For space',
  'للفيفا': 'for FIFA (world football body)',
  'للمزارعين': 'For farmers',
  'للمسالة': 'For the matter',
  'للمستقبل': 'For the future',
  'للمغفور': 'For the forgiven',
  'للموصوف': 'For the described',
  'للناطقين': 'For speakers',
  'للنص': 'for the text',
  'للوائح': 'for regulations',
  'لم': 'did not (past negation)',
  'لمؤسسة': 'For an institution',
  'لماذا': 'why',
  'لمتعلمي': 'For my learners',
  'لمدارس': 'For schools',
  'لمدة': 'for a duration of',
  'لمس': 'touch / hand-ball foul',
  'لمسابقة': 'For a contest',
  'لمسافات': 'For distances',
  'لمشكلة': 'For a problem',
  'لمناقشة': 'to discuss / for discussing',
  'لموضوعات': 'for topics / subjects',
  'لن': 'will not (future negation)',
  'لنصل': 'so we reach',
  'لنصوص': 'for texts / passages',
  'لنعرف': 'so we know',
  'لنيل': 'To get',
  'له': 'for him / has',
  'لها': 'for her / has',
  'لهم': 'for them',
  'لو': 'if / were it to',
  'لوائح': 'regulations / statutes',
  'لوح': 'board',
  'لوحة': 'painting / board',
  'لولي': 'for my guardian / parent',
  'لون': 'color',
  'لي': 'for me / mine',
  'لياقة': 'fitness',
  'ليس': 'is not',
  'ليست': 'she / it is not',
  'ليكون': 'to be',
  'ليلا': 'at night',
  'لينال': 'To get',
  'ليوناردو': 'Leonardo',
  'م': 'm (meter abbreviation)',
  'مؤنث': 'feminine gender',
  'مئة': '100 (one hundred)',
  'ما': 'what / which / not',
  'ماء': 'water',
  'مائة': 'one hundred',
  'مائية': 'aquatic / water',
  'ماجد': 'Majid',
  'ماجدا': 'Magda',
  'مادامت': 'as long as it is',
  'ماذا': 'what',
  'ماراثون': 'marathon',
  'مارس': 'practiced',
  'ماسح': 'scanner',
  'ماض': 'past tense',
  'مالوفة': 'familiar / well-known',
  'ماهر': 'skilled / talented',
  'مباراة': 'match / game',
  'مبارات': 'Matches',
  'مباريات': 'matches / games',
  'مباشر': 'direct / live',
  'مباشرة': 'directly',
  'مبتدأ': 'subject (topic of nominal sentence)',
  'مبتدئ': 'Beginner',
  'مبدئي': 'initial / preliminary',
  'مبدعا': 'Creative',
  'متابع': 'follower / fan',
  'متابعة': 'following / tracking',
  'متابعون': 'followers / fans',
  'متابعين': 'followers / fans',
  'متاح': 'Available',
  'متاكد': 'Sure',
  'متبادل': 'mutual / shared',
  'متباعد': 'spaced / distanced',
  'متتالية': 'consecutive / successive',
  'متجر': 'store / shop',
  'متحف': 'museum',
  'متحمسة': 'Excited',
  'متدرجة': 'Gradient',
  'متر': 'meter',
  'مترا': 'meters (accusative)',
  'مترابطا': 'coherent / connected',
  'متشوق': 'Excited',
  'متصل': 'connected / attached',
  'متصلة': 'attached (pronoun / letter)',
  'متعاون': 'cooperative / helpful',
  'متعمق': 'In-depth',
  'متقدمة': 'Advanced',
  'متقن': 'Perfectly done',
  'متمكن': 'proficient / master',
  'متميز': 'Outstanding',
  'متناسقة': 'Consistent',
  'متنوعة': 'diverse / varied',
  'متوسط': 'Average',
  'متوفرة': 'Available',
  'متى': 'when',
  'متين': 'sturdy / durable',
  'مثال': 'example',
  'مثل': 'such as / like',
  'مثلث': 'triangle',
  'مثلما': 'just like',
  'مثمر': 'Fruitful',
  'مثمرة': 'Fruitful',
  'مثنى': 'dual (two)',
  'مثيرة': 'exciting / thrilling',
  'مجازي': 'Metaphorical',
  'مجال': 'field / arena',
  'مجانا': 'Free',
  'مجانية': 'Free',
  'مجددا': 'Again',
  'مجرد': 'merely / just',
  'مجرور': 'genitive (prepositional object)',
  'مجزوم': 'jussive case (with Sukun)',
  'مجلة': 'magazine / periodical',
  'مجموع': 'total / aggregate',
  'مجموعات': 'groups',
  'مجموعة': 'group / team',
  'محادثة': 'Conversation',
  'محاكاة': 'simulation / mock exam',
  'محاولة': 'try',
  'محتار': 'Confused',
  'محتوى': 'Content',
  'محددة': 'specific / designated',
  'محرك': 'Engine',
  'محفوظة': 'preserved / reserved',
  'محمد': 'Muhammad',
  'محو': 'Erase',
  'محيط': 'perimeter / surrounding',
  'مخاطر': 'risks / hazards',
  'مخاطرها': 'its risks / hazards',
  'مخالف': 'infringing / contrary',
  'مخالفات': 'fouls / infractions',
  'مخالفة': 'foul / infraction',
  'مختبر': 'laboratory / lab',
  'مختلف': 'different / varied',
  'مختلفة': 'different / various (fem.)',
  'مخرج': 'articulation point / outlet',
  'مخصص': 'dedicated / customized',
  'مخطط': 'diagram / framework / outline',
  'مدافع': 'defender',
  'مدة': 'duration / period',
  'مدرب': 'coach',
  'مدربك': 'your coach',
  'مدربه': 'his coach',
  'مدربون': 'coaches',
  'مدرسة': 'school',
  'مدرستي': 'my school',
  'مدرسي': 'school-related',
  'مدرسية': 'school-related / educational',
  'مدعومة': 'Supported',
  'مدير': 'principal / director / manager',
  'مذاكرة': 'study / revision',
  'مذكر': 'masculine gender',
  'مذكور': 'mentioned',
  'مر': 'passed / elapsed',
  'مرئية': 'Visible',
  'مرات': 'times / instances',
  'مراجعة': 'review / revision',
  'مراحل': 'Stages',
  'مربع': 'square',
  'مربوطة': 'Curriculum Term',
  'مرة': 'once / time',
  'مرح': 'fun / joy',
  'مرحبا': 'welcome / hello',
  'مرحى': 'hurray! / bravo!',
  'مرر': 'pass the ball!',
  'مررت': 'passed the ball',
  'مرفوع': 'nominative case (with Dammah)',
  'مركز': 'center',
  'مرمى': 'goal',
  'مرور': 'passage / passing',
  'مريحا': 'Comfortable',
  'مريحة': 'Comfortable',
  'مريم': 'Maryam (proper name)',
  'مزدوج': 'Double',
  'مساء': 'evening',
  'مساءا': 'in the evening',
  'مسابقة': 'Contest',
  'مسار': 'path / curriculum track',
  'مساعد': 'assistant',
  'مساعدان': 'two assistant referees',
  'مساعدة': 'help / assistance',
  'مساعدين': 'assistants',
  'مسافة': 'distance',
  'مستخدما': 'using / employing',
  'مستدير': 'round / circular',
  'مستديرة': 'round / circular (fem.)',
  'مستطيل': 'rectangle / rectangular',
  'مستطيلا': 'rectangular',
  'مستعينا': 'seeking aid / utilizing',
  'مستقل': 'independent',
  'مستقيم': 'straight',
  'مستقيمة': 'straight (line)',
  'مستكشف': 'explorer',
  'مستمدة': 'derived',
  'مستوى': 'level',
  'مسموع': 'audio / heard / listened',
  'مشاجع': 'supporter / enthusiastic',
  'مشاعره': 'His feelings',
  'مشاهدة': 'Watch',
  'مشتركة': 'shared / common',
  'مشجع': 'supporter',
  'مشجعون': 'supporters',
  'مشجعين': 'fans / supporters',
  'مشكلة': 'Problem',
  'مشهورة': 'famous / renowned',
  'مشوق': 'engaging / exciting',
  'مصانع': 'factories',
  'مصطلح': 'Term',
  'مصغر': 'Miniature',
  'مصنفة': 'Classified',
  'مصنوعة': 'manufactured / made of',
  'مصور': 'Photographer',
  'مضارع': 'present tense (verb)',
  'مضرب': 'racket / bat',
  'مضمار': 'racetrack / circuit',
  'مطابق': 'matching / identical',
  'مطابقة': 'agreement / concord (verb-subject)',
  'مطاط': 'rubber',
  'مطبخ': 'kitchen',
  'مع': 'with',
  'مع_السلامة': 'goodbye',
  'معا': 'together',
  'معادلات': 'Equations',
  'معالجة': 'processing',
  'معايرة': 'calibration',
  'معايير': 'standards / benchmarks',
  'معبرا': 'Expressive',
  'معدودة': 'Numbered',
  'معرض': 'gallery / exhibition',
  'معرفة': 'knowledge',
  'معرفتك': 'your knowledge',
  'معرفية': 'Cognitive',
  'معك': 'with you',
  'معلق': 'Pending',
  'معلم': 'teacher (male)',
  'معلمة': 'teacher (female)',
  'معلومات': 'information',
  'معمقة': 'In-depth',
  'معنا': 'with us',
  'معنى': 'meaning / definition',
  'معهم': 'with them',
  'معي': 'with me',
  'مغلق': 'closed / indoor',
  'مغلقة': 'closed / indoor (court)',
  'مغمورا': 'immersed / sunken',
  'مفتوح': 'open / outdoor',
  'مفتوحة': 'Curriculum Term',
  'مفرد': 'singular',
  'مفروش': 'turfed / carpeted / covered',
  'مفصل': 'detailed / joint',
  'مفضل': 'favorite / preferred',
  'مفضلة': 'favorite (fem.)',
  'مفعول': 'object (grammatical)',
  'مفعول_به': 'direct object',
  'مفقودة': 'Missing',
  'مفكك': 'Disassembled',
  'مفهوم': 'concept / understood',
  'مفيد': 'useful / beneficial',
  'مفيدة': 'useful / beneficial (fem.)',
  'مقابلة': 'Interview',
  'مقاعد': 'seats / benches',
  'مقبولة': 'acceptable / valid',
  'مقترحات': 'Suggestions',
  'مقدار': 'amount / extent',
  'مقدر': 'estimated / latent (vowel)',
  'مقدرة': 'latent (mark) / capacity',
  'مقروء': 'readable / legible',
  'مقسمة': 'divided / partitioned',
  'مكان': 'place',
  'مكتبة': 'library / bookstore',
  'مكتمل': 'Complete',
  'مكتملة': 'Complete',
  'مكثفة': 'Intense',
  'مكون': 'component / ingredient',
  'ملابس': 'clothes / garments',
  'ملابسي': 'my clothes',
  'ملاحظات': 'notes / observations',
  'ملاحظة': 'note / observation',
  'ملاعب': 'pitches / stadiums',
  'ملامح': 'Features',
  'ملايين': 'millions',
  'ملزمة': 'study booklet / summary',
  'ملعب': 'pitch / field / stadium',
  'ملعبكم': 'your pitch',
  'ملعبنا': 'our pitch',
  'ملف': 'profile / file',
  'ملفات': 'profiles / files',
  'ملكة': 'queen / aptitude',
  'ملكية': 'possessive / ownership',
  'مليار': 'billion',
  'مليون': 'million',
  'مما': 'than what / of which',
  'ممارسة': 'practicing',
  'ممتاز': 'excellent / outstanding',
  'ممتعة': 'Enjoyable',
  'مميز': 'Distinctive',
  'مميزة': 'Featured',
  'من': 'from / who',
  'مناسب': 'suitable / appropriate',
  'مناسبة': 'suitable (fem.) / occasion',
  'منافسة': 'competition / contest',
  'مناقشة': 'discussion / debate',
  'منتبه': 'attentive / observant',
  'منجزة': 'Completed',
  'منذ': 'since / ago',
  'منزل': 'home / residence',
  'منشور': 'Published',
  'منشورا': 'Published',
  'منصوب': 'accusative case (with Fathah)',
  'منطقة': 'area / zone',
  'منفرد': 'solo / break-away',
  'منفردة': 'solo / break-away',
  'منك': 'from you',
  'منه': 'from him / it',
  'منها': 'from her / it',
  'منهاج': 'curriculum / syllabus',
  'منهم': 'from them',
  'مهاجم': 'striker / forward',
  'مهارات': 'skills',
  'مهارة': 'skill',
  'مهام': 'tasks / duties',
  'مهامك': 'Your tasks',
  'مهامي': 'My tasks',
  'مهر': 'colt / foal',
  'مهم': 'important',
  'مهمة': 'task / mission',
  'مواجهة': 'Confrontation',
  'مواضع': 'Placements',
  'موثوق': 'Reliable',
  'موجه': 'guided / directed',
  'موجودة': 'Exist',
  'موسعة': 'extended / expanded',
  'موسم': 'Season',
  'موسوعة': 'encyclopedia',
  'موضوع': 'Topic',
  'موضوعات': 'topics / themes',
  'موقع': 'Location',
  'مياه': 'water',
  'ميدالية': 'medal',
  'ميدان': 'arena / field',
  'ميزة': 'Advantage',
  'ميكانيكية': 'Mechanical',
  'ن': 'letter Noon',
  'نائما': 'Asleep',
  'نادي': 'club / sports club',
  'نام': 'slept',
  'نبات': 'Plant',
  'نبدأ': 'we begin',
  'نبرة': 'Tone',
  'نتحاور': 'We talk',
  'نتعلم': 'we learn',
  'نتناوله': 'We eat it',
  'نتيجة': 'Result',
  'نجاح': 'success',
  'نجد': 'We find',
  'نحت': 'Sculpture',
  'نحذفه': 'we delete it',
  'نحفظ': 'We save',
  'نحن': 'we',
  'نحو': 'towards / grammar',
  'نحوله': 'we transform it',
  'نحوي': 'grammatical',
  'نحوية': 'grammatical (fem.)',
  'نختبر': 'we test / assess',
  'نخسر': 'We lose',
  'ندعو': 'we invite / pray',
  'نرى': 'we see',
  'نزهة': 'picnic / outing',
  'نسبة': 'Ratio',
  'نستنتج': 'we deduce / infer',
  'نسخر': 'We make fun',
  'نسمي': 'We call',
  'نسيت': 'I forgot',
  'نشاط': 'activity / vitality',
  'نشط': 'Active',
  'نشطة': 'Active',
  'نشكر': 'We thank you',
  'نص': 'text',
  'نصا': 'a text / written passage',
  'نصف': 'half',
  'نصوص': 'texts / passages',
  'نصوصا': 'texts / reading passages',
  'نصيحتك': 'Your advice',
  'نضع': 'we place / put',
  'نضيف': 'we add',
  'نطاق': 'range / scope',
  'نطق': 'pronunciation / articulation',
  'نطقت': 'I spoke',
  'نطلق': 'We launch',
  'نظارة': 'Glasses',
  'نظافة': 'cleanliness',
  'نظام': 'system / order',
  'نظر': 'looked',
  'نظف': 'cleaned',
  'نظيف': 'clean',
  'نعم': 'yes',
  'نغير': 'we alter / change',
  'نفسه': 'himself / itself',
  'نفوس': 'Souls',
  'نقاط': 'points',
  'نقدي': 'Cash',
  'نقطة': 'point',
  'نقول': 'we say',
  'نقي': 'pure / fresh',
  'نلعب': 'we play',
  'نماذج': 'models / exemplars',
  'نمرح': 'We\\',
  'نموذج': 'model / sample',
  'ننصح': 'we recommend / advise',
  'ننطق': 'we pronounce / articulate',
  'نهائيا': 'Permanently',
  'نهار': 'daytime',
  'نهاية': 'end / finish line',
  'نهر': 'river',
  'نهي': 'Forbid',
  'نهيان': 'Nahyan',
  'نواتج': 'outcomes / results',
  'نوصي': 'we recommend / advise',
  'نوع': 'type / kind',
  'نوم': 'sleep',
  'ه': 'letter Haa / his',
  'هؤلاء': 'these (plural)',
  'ها': 'her / its / here',
  'هاء': 'Curriculum Term',
  'هات': 'give! / bring!',
  'هادئ': 'Quiet',
  'هادئة': 'Quiet',
  'هتاف': 'cheering / chanting',
  'هدر': 'growled',
  'هدف': 'goal / score',
  'هدفنا': 'our goal',
  'هدفهم': 'their goal',
  'هذا': 'this (masc.)',
  'هذه': 'this (fem.)',
  'هرم': 'Pyramid',
  'هكذا': 'thus / like this',
  'هل': 'is / does (question)',
  'هم': 'they',
  'هما': 'they (two)',
  'همزة': 'Curriculum Term',
  'هن': 'they (fem.)',
  'هنا': 'here',
  'هناك': 'there',
  'هندسية': 'geometric / engineering',
  'هو': 'he / it',
  'هواء': 'air / breeze',
  'هوايتك': 'Your hobby',
  'هوايتي': 'My hobby',
  'هوية': 'identity / heritage',
  'هي': 'she / it',
  'هيئة': 'shape / form / board',
  'هيا': 'come on! / let us go!',
  'هيكل': 'structure / framework',
  'و': 'and (conjunction)',
  'وأبوظبي': 'and Abu Dhabi',
  'وابلاغ': 'And inform',
  'واتعلم': 'And I learn',
  'واثق': 'confident',
  'واجب': 'duty / homework',
  'واجبات': 'homeworks / duties',
  'واجتياز': 'And pass',
  'واجهاد': 'and straining / fatigue',
  'واجهة': 'Interface',
  'واجهتها': 'I faced her',
  'واجهنا': 'Face us',
  'واحتفل': 'and I celebrate',
  'واحد': '1 (one)',
  'واحدة': '1 (one - fem.)',
  'واحراجهم': 'And embarrass them',
  'وارتدت': 'And she bounced',
  'واردة': 'mentioned / cited',
  'وارسالها': 'And send it',
  'واستخراج': 'And extract',
  'واسلوب': 'And style',
  'واضح': 'clear',
  'واضحة': 'clear (fem.)',
  'واعاين': 'And look',
  'وافتقد': 'And I miss',
  'وافكاره': 'And his thoughts',
  'وافهم': 'And understand',
  'واقيات': 'guards / protectors',
  'والآن': 'and now',
  'والأرجنتين': 'and Argentina',
  'والاداب': 'And etiquette',
  'والاستثناءات': 'And exceptions',
  'والاستماع': 'And listen',
  'والاشتراكات': 'And subscriptions',
  'والاضداد': 'And opposites',
  'والاطمئنان': 'And reassurance',
  'والاعجاب': 'And admiration',
  'والاقدام': 'And the feet',
  'والامن': 'And security',
  'والانجليزية': 'And English',
  'والانضباط': 'and discipline',
  'والانفجاري': 'and explosive',
  'والباس': 'And the bass',
  'والبلاغة': 'And eloquence',
  'والتاسيس': 'And the establishment',
  'والتجارب': 'And experiments',
  'والتحلي': 'And be sweet',
  'والتدقيق': 'and proofreading / verification',
  'والترجمة': 'And translation',
  'والتركيبي': 'and structural',
  'والتزم': 'and adhered to',
  'والتشكيل': 'and vowelization (harakat)',
  'والتصادم': 'and collision',
  'والتطور': 'And evolution',
  'والتعبير': 'And expression',
  'والتنسيق': 'and coordination',
  'والتواصلية': 'And communication',
  'والثقافة': 'And culture',
  'والجغرافيا': 'And geography',
  'والجوائز': 'And the prizes',
  'والحاجة': 'And the need',
  'والحاسمة': 'and decisive',
  'والحداثة': 'And modernity',
  'والخور': 'And the creek',
  'والخوف': 'And fear',
  'والدتي': 'My mother',
  'والدروس': 'And lessons',
  'والدعم': 'And support',
  'والدلالة': 'and semantic meaning',
  'والربط': 'and conjunction / connection',
  'والرسائل': 'And messages',
  'والرمز': 'And the symbol',
  'والروتين': 'And the routine',
  'والصغار': 'And the little ones',
  'والضمائر': 'and pronouns',
  'والعطاء': 'And giving',
  'والعلاج': 'And treatment',
  'والعنف': 'and violence / aggression',
  'والله': 'by Allah / truly',
  'والمتطلبات': 'and requirements',
  'والمجلة': 'And the magazine',
  'والمحادثة': 'And conversation',
  'والمدارس': 'And schools',
  'والمغامرة': 'And adventure',
  'والملبس': 'And the clothes',
  'والمواد': 'And materials',
  'والمواصفات': 'and specifications',
  'والموسيقى': 'And music',
  'والموصوف': 'and modified noun',
  'وامتطاء': 'And ride',
  'وانتاج': 'And production',
  'وانظر': 'and look!',
  'واهتمام': 'And interest',
  'واو': 'Curriculum Term',
  'وبسيطة': 'and simple',
  'وبعد': 'And after',
  'وبلاغي': 'And my rhetoric',
  'وبناء': 'and structure / building',
  'وبنية': 'and structure / syntax',
  'وتاريخه': 'And its history',
  'وتثبت': 'And it proves',
  'وتجارب': 'and experiences',
  'وتجعل': 'And make',
  'وتجنب': 'and avoiding / steering clear',
  'وتحدد': 'and specifies / determines',
  'وترتيب': 'And arrangement',
  'وترجمتها': 'And translated',
  'وتزويدك': 'and providing you with',
  'وتزيد': 'And it increases',
  'وتسالهم': 'And you ask them',
  'وتسقط': 'and drops / falls',
  'وتصحيح': 'And correct',
  'وتعبيره': 'And his expression',
  'وتغرس': 'and instills / plants',
  'وتفسير': 'And interpretation',
  'وتقديم': 'And submit',
  'وتم': 'And it was done',
  'وتمارين': 'And exercises',
  'وتمنحه': 'And you grant him',
  'وتنبيهات': 'And alerts',
  'وتوجيهاتك': 'And your guidance',
  'وتوجيهاته': 'And his directions',
  'وتوليد': 'And generating',
  'وثقة': 'And trust',
  'وثقته': 'I trusted him',
  'وجبات': 'meals',
  'وجبة': 'meal',
  'وجد': 'found',
  'وجدت': 'she found',
  'وجنيه': 'And a pound',
  'وجه': 'face / aspect',
  'وجود': 'presence / existence',
  'وحاول': 'And try',
  'وحفظ': 'And save',
  'وحل': 'And solve',
  'وداعا': 'farewell',
  'ودعم': 'And support',
  'وراء': 'behind',
  'ورجليه': 'and his feet / legs',
  'ورد': 'appeared / was mentioned',
  'وردت': 'received',
  'ورعاية': 'And care',
  'وزارة': 'ministry',
  'وزاري': 'ministerial / official',
  'وزارية': 'ministerial (fem.)',
  'وزن': 'Weight',
  'وسائل': 'Means',
  'وسابقة': 'and preceding / former',
  'وسام': 'badge / honor medal',
  'وسد': 'And block',
  'وسط': 'midfielder',
  'وسطى': 'middle / central',
  'وسلوك': 'and behavior / conduct',
  'وسمير': 'And Samir',
  'وشكاوى': 'And complaints',
  'وصفية': 'descriptive',
  'وصل': 'arrived / connection',
  'وصلت': 'she arrived',
  'وضح': 'Explain',
  'وضع': 'placing / position',
  'وطن': 'homeland / nation',
  'وطني': 'national / my homeland',
  'وظيفة': 'function / role',
  'وعدم': 'And not',
  'وغضب': 'And he got angry',
  'وفق': 'according to / in accordance with',
  'وفواتير': 'And bills',
  'وفي': 'And in',
  'وقالت': 'She said',
  'وقت': 'time',
  'وقع': 'fell / occurred',
  'وقعت': 'occurred / fell',
  'وقف': 'stood / paused',
  'وقفت': 'stood / paused (fem.)',
  'وقوانين': 'and regulations / rules',
  'وكلمة': 'and the word',
  'ولا': 'And no',
  'ولبس': 'And wear',
  'ولد': 'boy',
  'ولي': 'guardian / parent',
  'وما': 'And what',
  'ومبشر': 'And a missionary',
  'ومترددا': 'And hesitant',
  'ومتنوعة': 'and diverse / varied',
  'ومجسمات': 'And models',
  'ومجلة': 'And a magazine',
  'ومخارج': 'and articulation points',
  'ومراقبة': 'and monitoring',
  'ومرتبة': 'And tidy',
  'ومسجل': 'and registered / recorded',
  'ومشاركة': 'And share',
  'ومشوقة': 'And interesting',
  'ومضطربا': 'And troubled',
  'ومغطى': 'and covered / coated',
  'ومفروش': 'and carpeted / turfed',
  'ومكثفة': 'And intense',
  'وملا': 'And filled',
  'وممتعة': 'and enjoyable / fun',
  'ومملوءا': 'And full',
  'ومميز': 'and distinctive / special',
  'ومنع': 'And prevent',
  'وموفقة': 'and successful / blessed',
  'ون': 'plural suffix (-oon)',
  'ونضيف': 'and we add',
  'وننطقه': 'and we pronounce it',
  'ونون': 'and the letter Noon',
  'ونيل': 'And Neil',
  'وهدر': 'And he roared',
  'وهو': 'and he / and it',
  'وهي': 'and she / and it',
  'وواقيات': 'and shin guards / protective pads',
  'ووزنها': 'and its weight',
  'ويحظى': 'And it is enjoyed',
  'ويصبح': 'And it becomes',
  'ويصيغ': 'And formulate',
  'ويعلن': 'and announces',
  'ويقدم': 'And it offers',
  'ويقود': 'and leads',
  'وينظم': 'and organizes',
  'ي': 'letter Yaa / my suffix',
  'يأتي': 'he comes / arrives',
  'يأخذ': 'he takes',
  'يأكل': 'he eats',
  'يؤذي': 'It hurts',
  'يا': 'O (vocative particle)',
  'ياء': 'Curriculum Term',
  'يبدأ': 'he starts',
  'يبدو': 'It seems',
  'يبعد': 'Away',
  'يبلغ': 'reaches / amounts to',
  'يتحتم': 'It is inevitable',
  'يتدرب': 'he trains',
  'يتراوح': 'ranges / fluctuates',
  'يترك': 'Leaves',
  'يتصل': 'Calls',
  'يتطلب': 'it requires / demands',
  'يتعلم': 'he learns',
  'يتكون': 'consists of / is formed of',
  'يتناغم': 'harmonizes / blends',
  'يتنافس': 'competes',
  'يجب': 'must / should',
  'يجتمع': 'meet',
  'يجري': 'he runs',
  'يجعل': 'makes',
  'يجمع': 'he gathers / unites',
  'يجيء': 'he comes',
  'يجيب': 'he answers',
  'يحب': 'he loves / likes',
  'يحتاج': 'needs',
  'يحتسب': 'he awards / calculates',
  'يحتوي': 'Contains',
  'يحدث': 'happens / occurs',
  'يحدد': 'specifies / determines',
  'يحرز': 'scores',
  'يحصل': 'obtains / happens',
  'يحضر': 'he attends / prepares',
  'يحق': 'He is entitled',
  'يحقق': 'He achieves',
  'يحلل': 'Analyze',
  'يحمل': 'carries',
  'يخسر': 'he loses',
  'يد': 'hand',
  'يدل': 'indicates',
  'يدير': 'manages / officiates',
  'يديرون': 'they manage / officiate',
  'يذهب': 'he goes',
  'يرتب': 'he arranges / organizes',
  'يرتقي': 'He rises',
  'يرجع': 'he returns',
  'يرجى': 'Please',
  'يرسم': 'he draws / paints',
  'يرضي': 'Satisfies',
  'يركب': 'he rides',
  'يركز': 'Focus',
  'يركض': 'sprints',
  'يرمون': 'they throw / shoot',
  'يرمي': 'he throws / shoots',
  'يرى': 'he sees',
  'يريد': 'He wants',
  'يزرعها': 'He plants it',
  'يزيد': 'increases',
  'يسأل': 'he asks',
  'يسار': 'left (direction)',
  'يساعد': 'helps',
  'يستحقها': 'He deserves it',
  'يستخدم': 'is used',
  'يستطيع': 'is able to / can',
  'يستمتع': 'he enjoys',
  'يستمع': 'listens / is listening',
  'يستيقظ': 'he wakes up',
  'يسجل': 'scores',
  'يسدد': 'he shoots / kicks',
  'يسعد': 'He is happy',
  'يسمع': 'he hears',
  'يسمى': 'is called / named',
  'يشارك': 'he participates',
  'يشاهد': 'he watches / sees',
  'يشبه': 'resembles / is like',
  'يشترك': 'participates',
  'يشتركون': 'they participate',
  'يشرب': 'he drinks',
  'يشير': 'points to / refers',
  'يصبح': 'becomes',
  'يصل': 'reaches / arrives',
  'يصنع': 'creates / manufactures',
  'يضبط': 'adjusts',
  'يضحك': 'he laughs',
  'يضع': 'he puts / places',
  'يضم': 'includes / embraces',
  'يطرح': 'poses',
  'يطلب': 'He asks',
  'يطلق': 'launches / names',
  'يظهر': 'appears / shows',
  'يعتبر': 'is considered',
  'يعتمد': 'relies upon',
  'يعد': 'He promises',
  'يعرض': 'displays',
  'يعرف': 'he knows / recognizes',
  'يعطي': 'gives',
  'يعكس': 'reflects',
  'يعلم': 'he knows',
  'يعلمني': 'Teach me',
  'يعني': 'means',
  'يعود': 'returns',
  'يعيد': 'retells / repeats',
  'يغلق': 'he closes',
  'يفتح': 'he opens',
  'يفضل': 'he prefers',
  'يفهم': 'he understands',
  'يفوز': 'wins',
  'يفيد': 'It helps',
  'يقام': 'It takes place',
  'يقدم': 'Submit',
  'يقرأ': 'he reads',
  'يقضي': 'He spends',
  'يقف': 'stands',
  'يقفز': 'he jumps',
  'يقول': 'he says',
  'يقوم': 'undertakes / carries out',
  'يكتب': 'he writes',
  'يكلف': 'It costs',
  'يكمل': 'completes',
  'يكون': 'is / will be',
  'يلبس': 'He wears',
  'يلعب': 'he plays',
  'يلقنك': 'He teaches you',
  'يليق': 'It suits',
  'يمارس': 'practices',
  'يمتاز': 'Excellent',
  'يمتطي': 'He rides',
  'يمتلكون': 'They own',
  'يمرر': 'passes the ball',
  'يمكن': 'can / is possible',
  'يمكنني': 'I can',
  'يميز': 'distinguishes / differentiates',
  'يمين': 'right (direction)',
  'ين': 'plural / dual suffix (-een)',
  'ينام': 'he sleeps',
  'ينتج': 'produces / generates',
  'ينتهي': 'finishes / concludes',
  'ينجزها': 'completes it / accomplishes it',
  'ينحته': 'He sculpts it',
  'ينشر': 'Publish',
  'ينطق': 'pronounces / articulates',
  'ينظر': 'he looks',
  'ينظف': 'he cleans',
  'ينقسم': 'is divided',
  'ينقل': 'Transfer',
  'ينمو': 'It grows',
  'يوجد': 'exists / there is',
  'يوضع': 'It is placed',
  'يوكو': 'Yoko',
  'يوم': 'day',
  'يوما': 'a day (accusative)',
};
