// Complete Chapter 1: Ball Games (ألعاب الكرة) — Printed Pages 6-15
// Dual Arabic text with diacritics and exact English paragraph translations

class ChapterPage {
  final int pdfPage;
  final int printedPage;
  final String titleAr;
  final String titleEn;
  final List<String> paragraphsAr;
  final List<String> paragraphsEn;

  const ChapterPage({
    required this.pdfPage,
    required this.printedPage,
    required this.titleAr,
    required this.titleEn,
    required this.paragraphsAr,
    required this.paragraphsEn,
  });
}

const List<ChapterPage> kChapter1Pages = [
  ChapterPage(
    pdfPage: 8,
    printedPage: 6,
    titleAr: 'نَوَاتِجُ التَّعَلُّمِ - أَلْعَابُ الكُرَةِ',
    titleEn: 'Learning Outcomes - Ball Games',
    paragraphsAr: [
      'نَوَاتِجُ التَّعَلُّمِ: يَسْتَمِعُ وَيَفْهَمُ المَعْنَى الكُلِّيَّ فِي نُصُوصٍ بَسِيطَةٍ لِمَوْضُوعَاتٍ وَصْفِيَّةٍ مَأْلُوفَةٍ.',
      'يَسْتَمِعُ وَيُحَدِّدُ مَعْلُومَاتٍ مُحَدَّدَةً فِي نُصُوصٍ مُوَسَّعَةٍ وَبَسِيطَةٍ لِمَوْضُوعَاتٍ وَصْفِيَّةٍ مَأْلُوفَةٍ.',
      'يُعِيدُ سَرْدَ مَعْلُومَاتٍ تَفْصِيلِيَّةٍ مِنْ قِصَصٍ وَتَجَارِبَ شَخْصِيَّةٍ.',
      'يُنْتِجُ حَدِيثًا مُتَرَابِطًا مُسْتَخْدِمًا التَّنْغِيمَ وَالإِيقَاعَ الصَّحِيحَيْنِ.',
      'يَقْرَأُ وَيُحَدِّدُ النِّقَاطَ الرَّئِيسَةَ لِنُصُوصٍ مُوَسَّعَةٍ بَسِيطَةٍ.',
      'يَكْتُبُ نُصُوصًا بَسِيطَةً فِي مَوْضُوعَاتٍ وَصْفِيَّةٍ مَأْلُوفَةٍ.',
    ],
    paragraphsEn: [
      'Learning Outcomes: Listens and understands overall meaning in simple texts on familiar descriptive topics.',
      'Listens and identifies specific information in extended simple texts on familiar descriptive topics.',
      'Retells detailed information from stories and personal experiences.',
      'Produces coherent speech using correct intonation and rhythm.',
      'Reads and identifies main points of extended simple texts.',
      'Writes simple texts on familiar descriptive topics.',
    ],
  ),
  ChapterPage(
    pdfPage: 9,
    printedPage: 7,
    titleAr: 'قَامُوسِي',
    titleEn: 'My Glossary',
    paragraphsAr: [
      'الكُرَةُ: كُلُّ جِسْمٍ مُسْتَدِيرٍ. مِثَالٌ: هُنَاكَ أَنْوَاعٌ مُخْتَلِفَةٌ لِلْكُرَةِ فِي الْمَتْجَرِ.',
      'الحَجْمُ: المِقْدَارُ. مِثَالٌ: الكِتَابُ صَغِيرُ الحَجْمِ.',
      'النَّوْعُ: الصِّنْفُ. مِثَالٌ: الكُرَاتُ أَنْوَاعٌ كَكُرَةِ اليَدِ، وَكُرَةِ القَدَمِ.',
      'مُسْتَدِيرٌ: عَلَى هَيْئَةِ دَائِرَةٍ. مِثَالٌ: الكُرَةُ مُسْتَدِيرَةُ الشَّكْلِ.',
      'جَمَاعِيٌّ: يَشْتَرِكُ فِيهِ أَكْثَرُ مِنْ شَخْصٍ. مِثَالٌ: كُرَةُ الطَّائِرَةِ لُعْبَةٌ جَمَاعِيَّةٌ.',
      'فَرْدِيٌّ: يَقُومُ بِهِ فَرْدٌ وَاحِدٌ. مِثَالٌ: الرَّسْمُ نَشَاطٌ فَرْدِيٌّ.',
      'البَيْضَوِيُّ: أَحَدُ الأَشْكَالِ الَّذِي يُشْبِهُ البَيْضَةَ. مِثَالٌ: كُرَةُ الرَّجْبِي بَيْضَاوِيَّةٌ.',
      'المُبَارَاةُ: مُنَافَسَةٌ بَيْنَ فَرْدَيْنِ أَوْ مَجْمُوعَتَيْنِ. مِثَالٌ: سَتَكُونُ المُبَارَاةُ فِي كَأْسِ العَالَمِ بَيْنَ البَرَازِيلِ وَالأَرْجَنْتِينِ.',
    ],
    paragraphsEn: [
      'The Ball: Any spherical round body. Example: There are different types of balls in the store.',
      'Size: Magnitude / dimension. Example: The book is small in size.',
      'Type: Category / kind. Example: Balls have types like handball and football.',
      'Round: Shaped in the form of a circle. Example: The ball is round in shape.',
      'Collective (Team): In which more than one person participates. Example: Volleyball is a team sport.',
      'Individual (Solo): Carried out by a single individual. Example: Drawing is an individual activity.',
      'Oval: A shape resembling an egg. Example: A rugby ball is oval.',
      'The Match: A competition between two individuals or two groups. Example: The World Cup match will be between Brazil and Argentina.',
    ],
  ),
  ChapterPage(
    pdfPage: 10,
    printedPage: 8,
    titleAr: 'أَسْتَمِعُ - أَلْعَابُ الكُرَةِ',
    titleEn: 'I Listen - Ball Games',
    paragraphsAr: [
      'قَبْلَ الِاسْتِمَاعِ: أَقْرَأُ العُنْوَانَ، ثُمَّ أَتَحَدَّثُ مَعَ زَمِيلِي عَنْ أَنْوَاعِ الكُرَةِ الَّتِي أَعْرِفُهَا.',
      'الفِكْرَةُ الرَّئِيسَةُ لِلنَّصِّ المَسْمُوعِ هِيَ أَنْوَاعُ الرِّيَاضَاتِ وَالكُرَاتِ.',
      'أَثْنَاءَ الِاسْتِمَاعِ: أَسْتَمِعُ إِلَى النَّصِّ بِاسْتِخْدَامِ المَاسِحِ الضَّوْئِيِّ ثُمَّ أُنَاقِشُ أَفْرَادَ مَجْمُوعَتِي.',
      'الكُرَاتُ المَذْكُورَةُ فِي النَّصِّ: كُرَةُ القَدَمِ، كُرَةُ السَّلَّةِ، الرَّجْبِي، البُولُو، كُرَةُ المَاءِ، الجُولْف، كُرَةُ اليَدِ، البُولِينْج، كُرَةُ المَضْرِب.',
    ],
    paragraphsEn: [
      'Before Listening: I read the title, then discuss with my classmate the types of balls that I know.',
      'The central idea of the audio text is the types of sports and balls.',
      'During Listening: I listen to the text using the barcode scanner, then discuss with my group members.',
      'Balls mentioned in the text: Football, Basketball, Rugby, Polo, Water Polo, Golf, Handball, Bowling, Tennis/Racquetball.',
    ],
  ),
  ChapterPage(
    pdfPage: 11,
    printedPage: 9,
    titleAr: 'بَعْدَ الِاسْتِمَاعِ - أَبْحَثُ عَنِ الخَطَأِ',
    titleEn: 'After Listening - Error Hunting & Categorization',
    paragraphsAr: [
      'أَسْتَمِعُ مَرَّةً أُخْرَى، ثُمَّ أُشَارِكُ زَمِيلِي فِي اكْتِشَافِ الخَطَأِ فِي الجُمَلِ الآتِيَةِ:',
      '1. الكُرَاتُ كَثِيرَةٌ وَمُتَنَوِّعَةٌ، وَلَهَا الحَجْمُ نَفْسُهُ. (خَطَأ: لَهَا أَحْجَامٌ مُخْتَلِفَةٌ).',
      '2. كُرَةُ (البُولِينْج) كَبِيرَةٌ وَخَفِيفَةٌ. (خَطَأ: كُرَةُ البُولِينْج ثَقِيلَةٌ).',
      '3. كُرَةُ السَّلَّةِ تُشْبِهُ كُرَةَ التِّنِسِ. (خَطَأ: كُرَةُ السَّلَّةِ كَبِيرَةٌ وَكُرَةُ التِّنِسِ صَغِيرَةٌ).',
      '4. أَنْوَاعُ الكُرَاتِ الوَارِدَةِ فِي النَّصِّ عَشْرٌ.',
      'أُصَنِّفُ ثُمَّ أُقَارِنُ بَيْنَ أَنْوَاعِ الكُرَاتِ: بَيْضَاوِيَّةٌ، صَغِيرَةٌ، كَبِيرَةٌ، خَفِيفَةٌ، ثَقِيلَةٌ.',
    ],
    paragraphsEn: [
      'I listen once more, then partner with my peer to discover the error in the following sentences:',
      '1. Balls are numerous and varied, and have identical size. (Incorrect: they possess different sizes).',
      '2. A bowling ball is big and lightweight. (Incorrect: a bowling ball is heavy).',
      '3. A basketball resembles a tennis ball. (Incorrect: a basketball is large, whereas a tennis ball is tiny).',
      '4. The types of balls mentioned in the text are ten.',
      'I classify and compare between types of balls: oval, small, large, light, heavy.',
    ],
  ),
  ChapterPage(
    pdfPage: 12,
    printedPage: 10,
    titleAr: 'أَتَحَدَّثُ - اسْتِبْيَانُ أَلْعَابِ الكُرَةِ',
    titleEn: 'I Speak - Ball Games Survey & Opinions',
    paragraphsAr: [
      '١) أَمْلأُ الاسْتِبْيَانَ الآتِيَ؛ لأَعْرِفَ رَأْيَ مَجْمُوعَةٍ مِنْ زُمَلائِي: (أُحِبُّ، أُفَضِّلُ، لا أُحِبُّ، لا أُفَضِّلُ).',
      'اسْمُ اللُّعْبَةِ: كُرَةُ القَدَمِ (أُحِبُّهَا كَثِيرًا وَأَلْعَبُهَا مَعَ زُمَلائِي فِي مَلْعَبِ المَدْرَسَةِ).',
      'اسْمُ اللُّعْبَةِ: كُرَةُ السَّلَّةِ (أُفَضِّلُهَا لِأَنَّهَا تَحْتَاجُ إِلَى الرَّكْضِ السَّرِيعِ وَالقَفْزِ لِرَمْيِ الكُرَةِ فِي السَّلَّةِ).',
      'اسْمُ اللُّعْبَةِ: الرَّجْبِي (لُعْبَةٌ قَوِيَّةٌ جِدًّا تَسْتَخْدِمُ كُرَةً بَيْضَاوِيَّةَ الشَّكْلِ).',
      'اسْمُ اللُّعْبَةِ: الكِرِيكِت (لُعْبَةٌ مَشْهُورَةٌ تُلْعَبُ بِالمَضْرِبِ وَالكُرَةِ فِي مَيْدَانٍ مَفْتُوحٍ).',
      'اسْمُ اللُّعْبَةِ: كُرَةُ المَاءِ (لُعْبَةٌ مَائِيَّةٌ جَمَاعِيَّةٌ تُلْعَبُ دَاخِلَ حَوْضِ السِّبَاحَةِ).',
    ],
    paragraphsEn: [
      '1) I fill out the following survey to discover the viewpoints of my classmates: (I love, I prefer, I dislike, I do not prefer).',
      'Game: Football (I love it very much and play it with my classmates on the school pitch).',
      'Game: Basketball (I prefer it because it requires fast running and jumping to shoot the ball into the hoop).',
      'Game: Rugby (A powerful sport that employs an oval-shaped ball).',
      'Game: Cricket (A renowned game played with a bat and ball on an open field).',
      'Game: Water Polo (A collective water sport contested inside a swimming pool).',
    ],
  ),
  ChapterPage(
    pdfPage: 13,
    printedPage: 11,
    titleAr: 'مُخَطَّطُ الأَصَابِعِ الخَمْسَةِ وَالعَرْضُ التَّقْدِيمِيُّ',
    titleEn: 'Five-Finger Discussion Framework & Presentation',
    paragraphsAr: [
      '٢) أَسْتَخْدِمُ مُخَطَّطَ الأَصَابِعِ الخَمْسَةِ؛ لِمُنَاقَشَةِ زُمَلائِي فِي لُعْبَةِ الكُرَةِ المُفَضَّلَةِ:',
      'الإِبْهَامُ (لِمَاذَا؟): لِمَاذَا تُفَضِّلُ هَذِهِ اللُّعْبَةَ؟ (أُفَضِّلُهَا لِأَنَّهَا مُثِيرَةٌ وَتُعَلِّمُنَا التَّعَاوُنَ وَاللِّيَاقَةَ).',
      'السَّبَّابَةُ (مَتَى؟): مَتَى تَعَلَّمْتَ هَذِهِ اللُّعْبَةَ؟ (تَعَلَّمْتُهَا فِي المَدْرَسَةِ مُنْذُ عَامَيْنِ مَعَ مُعَلِّمِ الرِّيَاضَةِ).',
      'الوُسْطَى (مَا المَخَاطِرُ؟): مَا المَخَاطِرُ الَّتِي تُقَابِلُكَ فِي هَذِهِ اللُّعْبَةِ؟ (السُّقُوطُ، التَّصَادُمُ، وَإِجْهَادُ العَضَلاتِ).',
      'البِنْصِرُ (أَيْنَ؟): أَيْنَ تَلْعَبُ هَذِهِ اللُّعْبَةَ؟ (أَلْعَبُهَا فِي مَلْعَبِ الحَيِّ أَوْ فِي الصَّالَةِ الرِّيَاضِيَّةِ المُغْلَقَةِ).',
      'الخِنْصِرُ (كَمْ؟): كَمْ عَدَدُ اللاعِبِينَ فِي هَذِهِ اللُّعْبَةِ؟ (11 لاعِبًا فِي كُرَةِ القَدَمِ، وَ5 فِي كُرَةِ السَّلَّةِ).',
      '٣) أَسْتَخْدِمُ العَرْضَ التَّقْدِيمِيَّ / الجِهَازَ اللَّوْحِيَّ فِي تَقْدِيمِ عَرْضٍ مُشَوِّقٍ عَنْ لُعْبَةِ الكُرَةِ المُفَضَّلَةِ لِي وَلِزُمَلائِي.',
      'أَتَذَكَّرُ ضَمَائِرَ المِلْكِيَّةِ: رِيَاضَتِي (لِي) - رِيَاضَتُهُ (لَهُ) - رِيَاضَتُهَا (لَهَا) | لُعْبَتِي - لُعْبَتُهُ - لُعْبَتُهَا.',
    ],
    paragraphsEn: [
      '2) I utilize the five-finger framework to discuss my favored ball sport with my peers:',
      'Thumb (Why?): Why do you prefer this game? (I prefer it because it is thrilling and fosters teamwork and physical fitness).',
      'Index (When?): When did you learn this game? (I learned it at school two years ago with my PE teacher).',
      'Middle (What hazards?): What risks do you confront in this game? (Falling down, collision, and muscular strain).',
      'Ring (Where?): Where do you play this sport? (I play it at our neighborhood pitch or in the indoor gymnasium).',
      'Pinky (How many?): How many players participate in this game? (11 players in football, 5 in basketball).',
      '3) I employ a digital presentation / tablet to deliver an engaging showcase of my and my peers\' favorite ball game.',
      'I remember possessive pronouns: My sport - His sport - Her sport | My game - His game - Her game.',
    ],
  ),
  ChapterPage(
    pdfPage: 14,
    printedPage: 12,
    titleAr: 'أَقْرَأُ - السَّاحِرَةُ المُسْتَدِيرَةُ',
    titleEn: 'I Read - The Round Magician (Football)',
    paragraphsAr: [
      'كُرَةُ القَدَمِ هِيَ اللُّعْبَةُ الشَّعْبِيَّةُ الأُولَى فِي العَالَمِ، وَلِأَنَّهَا سَحَرَتْ عُقُولَ أَكْثَرَ مِنْ مِلْيَارِ مُتَابِعٍ حَوْلَ العَالَمِ سُمِّيَتْ بِالسَّاحِرَةِ المُسْتَدِيرَةِ.',
      'وَهِيَ لُعْبَةٌ جَمَاعِيَّةٌ وَلَيْسَتْ فَرْدِيَّةً، تَتَكَوَّنُ المُبَارَاةُ مِنْ فَرِيقَيْنِ فِي كُلٍّ مِنْهُمَا 11 لاعِبًا، يَفُوزُ الفَرِيقُ الَّذِي يُسَجِّلُ أَهْدَافًا أَكْثَرَ، وَتَعْتَمِدُ هَذِهِ الرِّيَاضَةُ عَلَى مَهَارَةِ القَدَمَيْنِ.',
      'أَهَمُّ مَا تَتَمَيَّزُ بِهِ كُرَةُ القَدَمِ: 1. كُرَةٌ مُسْتَدِيرَةُ الشَّكْلِ، مُحِيطُهَا 68 إِلَى 70 سم.',
      '2. المَلْعَبُ: قِطْعَةٌ مِنَ الأَرْضِ عَلَى شَكْلِ مُسْتَطِيلٍ مَفْرُوشٍ بِالعُشْبِ الأَخْضَرِ، طُولُهُ بَيْنَ 100 إِلَى 110 أَمْتَارٍ، وَعَرْضُهُ 64 إِلَى 75 مِتْرًا.',
      '3. المُبَارَاةُ: تَتَكَوَّنُ مِنْ شَوْطَيْنِ، مُدَّةُ كُلِّ شَوْطٍ 45 دَقِيقَةً، وَبَيْنَهُمَا اسْتِرَاحَةٌ مُدَّتُهَا 15 دَقِيقَةً.',
      '4. يَجِبُ أَنْ يَكُونَ فِي كُلِّ مُبَارَاةٍ 4 حُكَّامٍ.',
      '5. يَكُونُ اللَّعِبُ بِالأَرْجُلِ فَقَطْ مَا عَدَا حَارِسَ المَرْمَى الَّذِي يَسْتَطِيعُ اللَّعِبَ بِيَدَيْهِ وَرِجْلَيْهِ.',
      '6. لِكُلِّ فَرِيقٍ قَائِدٌ (كَابْتِن) لَهُ مَهَامٌّ خَاصَّةٌ.',
    ],
    paragraphsEn: [
      'Football is the foremost popular sport across the globe. Because it has enchanted the minds of over a billion followers worldwide, it was dubbed \'The Round Magician\' (The Enchantress).',
      'It is a collective team game, not an individual one. The match comprises two teams with 11 players each. The team scoring more goals wins, and this sport relies upon foot finesse.',
      'Key defining features of football: 1. A spherical ball with a circumference of 68 to 70 centimeters.',
      '2. The Pitch: A plot of terrain in the shape of a rectangle turfed with green grass, 100 to 110 meters long and 64 to 75 meters wide.',
      '3. The Match: Comprises two halves, each half lasting 45 minutes, with a 15-minute intermission between them.',
      '4. Every match must be overseen by 4 official referees.',
      '5. Play is conducted solely with the feet, except for the goalkeeper who may play with hands and feet.',
      '6. Each team has a team captain (skipper) assigned specific duties.',
    ],
  ),
  ChapterPage(
    pdfPage: 15,
    printedPage: 13,
    titleAr: 'بَعْدَ القِرَاءَةِ - وَقْتُ المُنَاقَشَةِ',
    titleEn: 'After Reading - Discussion & Comprehension',
    paragraphsAr: [
      'أَتَعَاوَنُ مَعَ زَمِيلِي فِي اخْتِيَارِ الإِجَابَةِ الصَّحِيحَةِ لِأُكْمِلَ الجُمَلَ الآتِيَةَ:',
      'عَدَدُ مُتَابِعِي كُرَةِ القَدَمِ حَوْلَ العَالَمِ: أَكْثَرُ مِنْ مِلْيَار مُتَابِعٍ.',
      'لُعْبَةُ كُرَةِ القَدَمِ لُعْبَةٌ: جَمَاعِيَّةٌ.',
      'المَلْعَبُ قِطْعَةٌ مِنَ الأَرْضِ عَلَى شَكْلِ: مُسْتَطِيلٍ.',
      'عَدَدُ الحُكَّامِ فِي كُلِّ مُبَارَاةٍ: أَرْبَعَةُ حُكَّامٍ.',
      'المَهَارَةُ الأَسَاسِيَّةُ فِي هَذِهِ الرِّيَاضَةِ: مَهَارَةُ القَدَمَيْنِ وَالتَّعَاوُنُ الجَمَاعِيُّ.',
    ],
    paragraphsEn: [
      'I collaborate with my peer to select the correct answer to complete the following sentences:',
      'Number of football fans worldwide: more than one billion fans.',
      'The game of football is a: team (collective) sport.',
      'The playing pitch is a plot of ground shaped like a: rectangle.',
      'Number of referees in every match: four referees.',
      'The essential skill in this sport: footwork skill and collective teamwork.',
    ],
  ),
  ChapterPage(
    pdfPage: 16,
    printedPage: 14,
    titleAr: 'أَكْتُبُ - قَبْلَ الكِتَابَةِ (التَّخْطِيطُ)',
    titleEn: 'I Write - Pre-Writing Planning Questions',
    paragraphsAr: [
      '١) أَجْلِسُ مَعَ أَفْرَادِ مَجْمُوعَتِي لِلتَّخْطِيطِ لِلْكِتَابَةِ مُسْتَعِينًا بِالأَسْئِلَةِ عَلَى كُلِّ كُرْسِيٍّ:',
      'مَا لُعْبَتُكَ المُفَضَّلَةُ؟ وَلِمَاذَا؟ (لُعْبَتِي المُفَضَّلَةُ هِيَ كُرَةُ القَدَمِ لِأَنَّهَا تُعَلِّمُنَا التَّعَاوُنَ وَاللِّيَاقَةَ).',
      'صِفْ مَكَانَ اللَّعِبَةِ؟ (المَلْعَبُ مُسْتَطِيلُ الشَّكْلِ، مَفْرُوشٌ بِالعُشْبِ الأَخْضَرِ، وَفِيهِ مَرْمَيَانِ وَشِبَاكٌ).',
      'كَمْ عَدَدُ اللاعِبِينَ فِي هَذِهِ اللَّعِبَةِ؟ (11 لاعِبًا فِي كُلِّ فَرِيقٍ، أَيْ 22 لاعِبًا فِي المَلْعَبِ).',
      'مَا فَوَائِدُ اللُّعْبَةِ؟ وَمَا مَخَاطِرُهَا؟ (الفَوَائِدُ: تَقْوِيَةُ الجِسْمِ وَالصِّحَّةِ | المَخَاطِرُ: الإِصَابَاتُ وَالتَّصَادُمُ عِنْدَ الإِهْمَالِ).',
      'مَا شُرُوطُ اللُّعْبَةِ؟ (الِالْتِزَامُ بِقَوَانِينِ الفِيفَا، الِاحْتِرَامُ المُتَبَادَلُ، وَتَجَنُّبُ الأَخْطَاءِ وَالعُنْفِ).',
      'مَا أَدَوَاتُ اللُّعْبَةِ؟ (كُرَةٌ مُسْتَدِيرَةٌ، حِذَاءٌ رِيَاضِيٌّ خَاصٌّ، وَوَاقِيَاتُ السَّاقَيْنِ).',
    ],
    paragraphsEn: [
      '1) I sit with my group members to plan for writing, guided by the prompts on each chair:',
      'What is your favorite game? And why? (My favorite game is football because it teaches us cooperation and physical fitness).',
      'Describe the game venue? (The pitch is rectangular, turfed with green grass, equipped with two goals and nets).',
      'How many players participate? (11 players per team, making 22 players on the pitch).',
      'What are the game benefits? And risks? (Benefits: strengthening physical body and health | Risks: injuries and collisions when careless).',
      'What are the game regulations? (Adhering to FIFA rules, mutual respect, and avoiding aggressive fouls).',
      'What are the game tools? (A spherical ball, specialized athletic boots, and protective shin guards).',
    ],
  ),
  ChapterPage(
    pdfPage: 17,
    printedPage: 15,
    titleAr: 'أَسْتَعِينُ بِالتَّرَاكِيبِ وَأَحْتَفِلُ بِكِتَابَتِي',
    titleEn: 'Connective Structures & Publishing My Writing',
    paragraphsAr: [
      '٢) أَسْتَعِينُ بِالتَّرَاكِيبِ الآتِيَةِ لِأَكْتُبَ نَصًّا مُتَرَابِطًا:',
      'يَجِبُ أَنْ: (يَجِبُ أَنْ يَتَدَرَّبَ اللاعِبُونَ بِانْتِظَامٍ لِتَحْقِيقِ الفَوْزِ).',
      'كَذَلِكَ: (يَحْتَاجُ الفَرِيقُ إِلَى مَهَارَاتٍ بَدَنِيَّةٍ، وَكَذَلِكَ إِلَى خُطَّةٍ تكتيكية ذَكِيَّةٍ).',
      'كَمَا أَنَّ: (كَمَا أَنَّ الرُّوحَ الرِّيَاضِيَّةَ أَهَمُّ مِنْ مُجَرَّدِ تَسْجِيلِ الأَهْدَافِ).',
      'أَيْضًا: (يُحِبُّ زَايِدٌ كُرَةَ القَدَمِ، وَيُحِبُّ أَيْضًا السِّبَاحَةَ وَالجَرْيَ).',
      'عَلَى الرَّغْمِ مِنْ: (عَلَى الرَّغْمِ مِنْ صُعُوبَةِ المُبَارَاةِ، اسْتَطَاعَ فَرِيقُنَا الفَوْزَ بِالكَأْسِ).',
      '٣) أَحْتَفِلُ بِكِتَابَتِي: أُعِيدُ الكِتَابَةَ بَعْدَ التَّنْقِيحِ ثُمَّ أَنْشُرُ مَا كَتَبْتُ مَعَ زُمَلائِي فِي مَجَلَّةِ المَدْرَسَةِ الرِّيَاضِيَّةِ (عَالَمُ الرِّيَاضَةِ).',
    ],
    paragraphsEn: [
      '2) I use the following sentence connectives to compose a coherent text:',
      'Must / Necessary that: (Players must train regularly to achieve victory).',
      'Likewise / Also: (The team requires physical stamina, and likewise requires a clever tactical strategy).',
      'In addition / Just as: (In addition, sportsmanship is far more vital than merely scoring goals).',
      'Also / Too: (Zayed loves football, and also loves swimming and running).',
      'Despite / Although: (Despite the difficulty of the match, our team managed to win the trophy).',
      '3) I celebrate my writing: I rewrite after editing, then publish what I wrote alongside my peers in the school sports magazine (Sports World).',
    ],
  ),
];
